### ISSUE TITLE
Randomization in functions

### ISSUE THREAD

**Issue by TApicella** [inkle/ink#11]
It would be nice to have some form of randomization within functions. I was hoping something like 
`VAR temp_pos = {~1|2|3|4|5}`
would work, but it doesn't seem to be possible using the randomization options used by the printing features.

**Comment by joningold** [comment]
You can do:

{shuffle:
- ~ x = 1
- ~ x = 2
... Etc ...
}

Using a multi line block (apologies, these had fallen out of the
documentation until today.) You could also wrap this up into a function.

(Failing all that, you can build an external function that calls the game
to set a random variable.)

(Also note that for temporary values it may be better to use ~ temp x = ...
rather than VAR x = ...)

**Comment by TApicella** [comment]
Ahh, didn't realize that shuffle was a keyworded concept. Thank you! I am greatly enjoying using ink so far, been coding all weekend.

**Comment by joningold** [comment]
Awesome :)
