### ISSUE TITLE
[Question] Getting a variables list.

### ISSUE THREAD

**Issue by naam00** [inkle/ink#114]
(I'm new to Github Issues, but I can't find another forum-type information-base for Ink, so trying here)

I'm looking for a way to get a list of variable names from the variableState object, I think it is impossible right now? In my project prototype I need to make sure all flags within Ink are set to the same value as those within the rest of my project. Was hoping to do this automatically by comparing the two lists of flagnames, but I can't find a way to get at something like that from Ink?

Feel free to direct me to more appropriate forumalikes for questions like this, thanks!
Naam

**Comment by joethephish** [comment]
No problem, we're using github issues as a forum anyway since it's a good central place and has all the right features, it's just a bit surprising / unintuitive!

The `variablesState` object is actually an `IEnumerable`, so it's possible to use a `foreach` on it, and it'll iterate through the global variable names.

**Comment by naam00** [comment]
Ah Thanks! Seems I tried to do that in a way too convoluted manner. Works now! Very good, exactly what I need.

And since we can use forum-talk: thanks for making this available you guys : )!

**Comment by joethephish** [comment]
No problem, and our pleasure!
