### ISSUE TITLE
Ink Compiler Crash

### ISSUE THREAD

**Issue by naam00** [inkle/ink#115]
Using Inky, I can make the Ink compiler crash consistently with:

```
VAR someVar = false

{someVar:
    {!
        Some text
        ->END
    }
}

->END
```

Should be legal code, right?

**Comment by naam00** [comment]
Alright, seems this is actually enough:
`{!}
`
or
```
{!
}
```

**Comment by joethephish** [comment]
Thanks! Good catch :)

**Comment by joethephish** [comment]
Fixed in 2408003e887e201ff1ec21336d143476c99d6bb6.

In your first example, you would need a `-` before "Some text" to denote a multi-line sequence element.

As a side note, it's debatable whether we should allow sequences with single elements. They can be ambiguous with normal inline logic, and don't bring anything. For example, `{!x}`: Is that `{not x}` or `{once:x}`? For that matter, `once` looks like a variable in that example, like `{myVar:this is true}`.

So, we should probably disallow that at some point in future.

**Comment by naam00** [comment]
Yes : ) managed to learn the correct syntax after the post. Thanks! Still, it shouldn't crash the compiler.

The confusing thing for me is that I had a similarly setup language years ago (generative text thingy, never went anywhere) that fully allowed formatting within list-structures like that. So

`{s:someParam | option1 | option2 | option3 }
`
...worked the same as

```
{s:someParam 
	| option1
		multiline text goes here
	| option2 
	| 
		option3 
}

```
In my case I enforced all snippets to be structured like `{x:code|content}` where `x` denoted the type of structure, `code` denoted either a parameter (or boolean string) or a specification of `x` (and could be left blank), and the `|` before the actual content was enforced. I guess that lead to less ambivalence, though I had to use `or` instead of `||` of course : ).

So with that in mind I was expecting newlines not to matter. Changing syntax just to deal with newlines takes a little getting used to! It means you sometimes will have to switch syntax when a structure is growing out to be something more than a line during authoring.

**Comment by joethephish** [comment]
Yeah, we considered using `|` for multi-line sequences, but in the end, we preferred `-` for readability, though I definitely understand the arguments for redrafting etc. Similarly, we prioritised compactness over consistency/ambiguity. Again, just a matter of personal choice/taste, I think!

**Comment by naam00** [comment]
Fair point! Just a matter of getting used to. Thanks!
