### ISSUE TITLE
documentation for json files?

### ISSUE THREAD

**Issue by beeglebug** [inkle/ink#12]
I've been taking a look at ink this weekend (great work btw, and kudos for open sourcing), with an eye to pitching in towards a javascript runtime (i'm a web guy and would love to play ink games in the browser, it seems such a natural fit with the json output!).

My main stumbling point so far has been the json files themselves, they seems very complex and verbose, even when compiling the smallest hello world example.

I know you have said that there are changes on the way to simplifying the format, so i'm wary of diving too deep or making any suggestions, but I guess i'm wondering if you have either of:

  * A timescale on the refactor
  * Any documentation on the compiled format that people like me could use when tinkering with the language?

In case you are interested, the bit that confuses me the most is:
```
[
        {
          "cmd": "EvalStart"
        },
        {
          "cmd": "BeginString"
        },
        {
          "div": ".^.s",
          "push": "func"
        },
        {
          "cmd": "EndString"
        },
        {
          "cmd": "BeginString"
        },
        ".\"",
        {
          "cmd": "EndString"
        },
        {
          "cmd": "EvalEnd"
        }

]
```
Which seems to be repeated almost once for every line of text. I think I get what it's doing, but it seems like a hell of a lot of boilerplate for what I assume is basically printing a string? (i'm assuming some part of the more advanced features of the language require the verbosity?).

Anyway, thanks for reading, and sorry for the long non-issue (and the slight whiff of entitlement), i'd just REALLY love to get involved on the js side, but don't want to waste time if it's all going to change under me in the immediate future.

**Comment by joethephish** [comment]
Really appreciate the enthusiasm, I'm excited to see that you're interested in helping out with a JS runtime.

In answer to your questions though: I imagine it'll be a few months until we're really happy with the runtime stability. There are a few larger features that can probably wait until a big new version, but we've been changing it fairly substantially recently, so I'd want to be sure that we're not constantly moving the goal posts.

As you've found, the JSON is super verbose at the moment, and that's definitely going to change/improve a lot when I have time to do a pass on it, hopefully sooner rather than later. So at the very least, you should wait for that.

Also, just to be sure, have you seen [this doc that gives an overview of the architecture](https://github.com/inkle/ink/blob/master/Documentation/ArchitectureAndDevOverview.md)?

**Comment by aloisdg** [comment]
Yaml could be a nice alternative to json. It is less verbose, human friendly and offers a compatibility with json.

**Comment by joethephish** [comment]
Note that I've now written up some documentation for the JSON format, which I've also re-written today:

https://github.com/inkle/ink/blob/master/Documentation/ink_JSON_runtime_format.md

It doesn't describe exactly how the engine steps through the content, but it might help as a starting point.
