### ISSUE TITLE
printing variables as option text seems bugged

### ISSUE THREAD

**Issue by Mixwhelan** [inkle/ink#124]
I can't seem to print variables as option text without having some issues even with a \ before

This:
```
-   (return)"So you watched anything else?"
~ temp option = ""
{shuffle:
 - ~option = "Yeah."
 - ~option = "Actually I have."
 - ~option = "Now that I think of it, yeah."
}
*    \ {option}.[]
    ->Qs
*   Nope, that's it.[] ->topics
```

Crashes the compiler with this crash report:

Unhandled Exception: 
Ink compiler had an unexpected error ☹

System.Exception: RUNTIME ERROR: Variable 'option' could not be found in context '-1'. This shouldn't be possible so is a bug in the ink engine. Please try to construct a minimal story that reproduces the problem and report to inkle, thank you!
   at Ink.Runtime.VariablesState.GetRawVariableWithName(String name, Int32 contextIndex)
   at Ink.Runtime.VariablesState.GetVariableWithName(String name, Int32 contextIndex)
   at Ink.Runtime.VariablesState.GetVariableWithName(String name)
   at Ink.Runtime.Story.PerformLogicAndFlowControl(Object contentObj)
   at Ink.Runtime.Story.Step()
   at Ink.Runtime.Story.ContinueInternal()
   at Ink.Runtime.Story.Continue()
   at Ink.CommandLinePlayer.EvaluateStory()
   at Ink.CommandLinePlayer.Begin()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)

**Comment by facelesspanda** [comment]
From what I can get from your script, it looks like a scope error. You define your option variable in a gather point and then use it in an option after that. I'm not an ink developper, but the "temp" keyword may be the reason you get an error because it may constrain the scope to a single block of flow (options and gathers in a weave being different flow blocks).

Try using a global variable instead? (Plus it might be beneficial if you have several points in the story where you need such a variable)

Although what you want can also be accomplished with a simple random list directly in the option :
```
-   (return)"So you watched anything else?"
*    \ {~Yeah|Actually I have|Now that I think of it, yeah}.[]
    ->Qs
*   Nope, that's it.[] ->topics
```
This script should have the exact behaviour that you expected

**Comment by joethephish** [comment]
More minimal repro:

```
~ temp optText = "option text"
* \ {optText}
```

Based on the above repro, it's not a scope issue @facelesspanda, although that was a good guess! I'll look into it...

**Comment by joethephish** [comment]
Oh, and in answer to your question @facelesspanda about what the `\` is for: it's to ensure that `{optText}` gets treated as content, rather than as a condition for the option. Since an option expects a sequence of bullet(s)  -> label -> condition -> content, it ensure that it jumps straight to content, since `\  ` is content.

**Comment by joethephish** [comment]
This one was a pretty tough, required rewiring the way that choices work. Fixed in 6d4f42b618a31780f5ee067dfb3256c0e9c23a0e, will make it into next ink/inky releases.

**Comment by y-lohse** [comment]
The fact that this kind of changes has no impact on the runtime makes me very happy, FWIW.

**Comment by joethephish** [comment]
Thanks, yeah :-) I certainly did consider that while deciding on implementation!

**Comment by joethephish** [comment]
Fix included in [latest inky build](https://github.com/inkle/inky/releases/tag/0.4.0).
