### ISSUE TITLE
Feature Request: get the paths of all the addressable story content in an ink.

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#128]
So here's our use-case. Much of our story occurs between talking characters. Chunks of text are annotated with character information, such as mood, pose.

During production, we would like the ability for our artists and writers to quickly audit that the text has the correct annotations by previewing our character visuals along-side the text. 

However, some of parts of the story are access via natural gameplay and (even with debug tools) it would take a long time to get the game in the right state to reach that piece of content. Ideally, we'd build a preview tool that just jumps between all the different knots in a file. We'd be able to easily build our preview tool if we had access to a IEnumerable<string> of the addressable pieces of story content.

How big of a request is this? Is it a simple matter of exposing some internals, or would it be a bigger undertaking than that?

Thanks again for the hard work!
-Jonathan

**Comment by joethephish** [comment]
Hey Jonathan,

So, right now it's sort of possible, but it would be a bit hacky. An ink story gets compiled down into a hierarchy of containers which are a cross between a dictionary and an array. The root container's dictionary has a set of keys which will include all the knots, but it may contain other things as well, since the structure is transformed when compiled. The containers for those knots will then contain the stitches, which again may contain other things.

In the long term it's probably a good idea for us to provide this metadata properly to the runtime somehow, but in the meantime, if you want to try to hack something in: add a property to the `Story` class that accesses `mainContentContainer.namedOnlyContent`. This dictionary's keys will includes all the knot and function names in the story.

**Comment by nullObjectPtr** [comment]
Thanks for pointing me in the right direction. We'll do as you suggested.
