### ISSUE TITLE
web export no interaction

### ISSUE THREAD

**Issue by papataci** [inkle/ink#133]
hello inklers,

i've web exported a project, but the resulting page shows only the title and no link to start the story, both locally and uploaded to web server

project works just fine in inky editor

any ideas, please?

**Comment by joethephish** [comment]
Sorry about that! Could you see if there are any error messages in the developer console?

(cc @y-lohse)

**Comment by papataci** [comment]
i've opened the console, there's only this warning:

ace-min.js:1 Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message

i've noticed that exporting my project only 4 files are created:
index.html
ink.iife.js
main.js
style.css

when exporting "The Intercept" creates 5:
index.html
ink.iife.js
main.js
style.css
Untitled.js

**Comment by joethephish** [comment]
Oh! Okay, it seems the story's JavaScript isn't being generated, I would guess because of some error that isn't getting reported for some reason. Would you be happy to share your story file here? It would be really helpful if you could narrow it down until you find what's going wrong...

**Comment by papataci** [comment]
allright joethephish, here's the archive
[Scenes.zip](https://github.com/inkle/ink/files/381115/Scenes.zip)

**Comment by joethephish** [comment]
Ahha, found it. It's because your main .ink file is called "main.ink", which is how we derive the name of your story file, so it ends up being called "main.js". **However**, that's also the name that we chose for the small javascript file that contains logic for running the story, so one ends up being overwritten by the other. If you rename your main.ink to something else, it should work. I'll decide on a scheme to avoid the conflict in future.

By the way, I couldn't help but notice that you seem to be using a pattern of doing something like:

```
== init ==
Your init stuff
-> back_from_init

// In main.ink:
-> init
== back_from_init
```

The way to do this properly is with tunnels:

```
== init ==
Your init logic 
->->

// In main.ink
-> init ->
```

Cheers!

**Comment by papataci** [comment]
Thank you very much, this fixes the problem.

Ok for the tunnels, i didn't understand their use

cheers
