### ISSUE TITLE
Parsing functionality exposed via DLL

### ISSUE THREAD

**Issue by wiseman** [inkle/ink#137]
It looks like there's no way to programmatically parse ink files, is that correct?  You need to call the inklecate.exe?

If that's true, what do you think about adding the parser API to the DLL?  I'm using a custom extension/engine for Ink, and it would be convenient to be able to parse to JSON without having to parse the output of the exe to see if there are errors, warnings, etc.

**Comment by joethephish** [comment]
I'm not entirely sure I understand your use-case? You want to programatically be able to call the parser... for what exactly?

For both the ink-unity-integration and within Inky itself we do indeed parse the output of inklecate. (Unix style I guess?)

**Comment by wiseman** [comment]
I programmatically call the parser because I don't want my authors to have to deal with having to manually compile Ink to JSON (I was a little surprised that I couldn't load an Ink file directly using the API).  I actually have a custom authoring language and runtime environment based on Ink, so given an Ink file I preprocess it, compile the result to JSON, and run that--from the user's point of view they're just running a script in my custom language.

My motivations for wanting an API instead of having to run a separate executable are really relatively minor: 1. It's inconvenient to parse output (and changes in program output aren't always treated as potentially breaking API changes with regards to versioning, so it happens more often/without as much warning) for errors & warnings; 2. It's a slight pain to have to check what platform I'm on and either invoke inklecate.exe directly or invoke it via `mono`; 3. The exe is an additional dependency that I need to be able to locate, or have the user install on the `PATH`.  Basically, there are a few more opportunities for something to go wrong.

Looking at the command line tool code, it looks like there already is a pretty easy to use API for compilation, and I was hoping it might already be exposed in the DLL.  When I saw that it wasn't, I made it work anyway, but it did take a day or two to debug everything across 3 platforms. I opened this issue because I thought other people might have a similar desire.

**Comment by joethephish** [comment]
Okay, interesting. Glad you made it work okay in the end. Did you do so by exposing what you needed and building a new parser DLL or just by interfacing via text with inklecate, in the end?

I hadn't considered that before, and it does indeed sound like it could be a more robust solution for inky too...

**Comment by wiseman** [comment]
I just executed inklecate and parsed the output.

**Comment by wizardsmoke** [comment]
I am using the Unity integration for Ink, and have a similar use case.  I would like users (authors) to be able to use their source files directly, instead of having to manually compile them before using them.  A way to programmatically compile a source file at runtime would be very useful.  This original post is a few years old... maybe something like this already exists?

**Comment by joethephish** [comment]
This is now supported! See [the Compiler class](https://github.com/inkle/ink/blob/master/compiler/Compiler.cs).

Off the top of my head, you just need to do `var compiler = new Ink.Compiler(sourceInk, options);` then `compiler.Compile();`. In the `Options` class, `pluginNames` you can ignore (it's an old feature we didn't end up taking any further), and `countAllVisits` doesn't do anything anymore, I should remove it. The `filename` option is purely cosmetic for error messages.

**Comment by wizardsmoke** [comment]
Yay!  Thanks for the quick response! :)

**Comment by wizardsmoke** [comment]
I am running into an issue with this.  In order to use the Compiler class, I had to enable the ink_compiler dll in Unity.  This allowed me to reference the Compiler class and construct a Compiler object.  However, when I tried to then call `compiler.Compile();`, I got the following error:

`Assets\Test.cs(12,9): error CS0012: The type 'Story' is defined in an assembly that is not referenced. You must add a reference to assembly 'ink-engine-runtime, Version=1.0.7111.15053, Culture=neutral, PublicKeyToken=null'.`

This prompted me to then enable the ink-engine-runtime dll in Unity.  Doing generated two further errors:

`Assets\Plugins\Ink\Example\Scripts\BasicInkExample.cs(59,28): error CS0433: The type 'Choice' exists in both 'Ink-Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ink-engine-runtime, Version=1.0.7111.15053, Culture=neutral, PublicKeyToken=null'`

and

`Assets\Plugins\Ink\Example\Scripts\BasicInkExample.cs(98,9): error CS0433: The type 'Story' exists in both 'Ink-Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ink-engine-runtime, Version=1.0.7111.15053, Culture=neutral, PublicKeyToken=null'`

I'm not sure how to proceed.  It feels like I am missing something obvious.

**Comment by joethephish** [comment]
In latest engine you shouldn't need to use DLLs at all at runtime - just include the source. That will allow you to also access any `internal` marked stuff rather than just `public`. Hmm though now I think about it, we may not have released that in an official version yet, maybe it's only in master.

**Comment by wizardsmoke** [comment]
Yeah, this is with a fresh download of the latest Unity Integration package, as of about a month ago.

**Comment by wizardsmoke** [comment]
Adding the `compiler` directory from master to the `Assets/Plugins/Ink` directory generated some compile errors about various types being inaccessible due to their protection levels.

**Comment by wizardsmoke** [comment]
Please let me know how to properly include the compiler code, or if you are planning to add it to an official version of the Ink Unity Integration.  Thanks for your help with this :)

**Comment by wizardsmoke** [comment]
I was able to resolve the compile errors by changing a bunch of access modifiers from internal to public, but this is obviously not ideal :/

**Comment by joethephish** [comment]
Hmmm this shouldn’t be necessary if they’re being accessed from the same assembly! You should make sure you’re including the whole source from master, not mixing and matching a runtime DLL with compiler source or something....

**Comment by wizardsmoke** [comment]
Ah, it looks like I just put the compiler code into the wrong directory.  It was in the `Assets/Plugins/Ink` directory when it should have been in the `Assets/Plugins/Ink/InkRuntime` directory.  The InkRuntime directory has a file called `Ink-Runtime.asmdef` that appears to configure the `Ink-Runtime` assembly such that all files in that directory are included in the assembly.
