### ISSUE TITLE
else if doesn't work if the first condition is on the same line as the opening brace

### ISSUE THREAD

**Issue by wilg** [inkle/ink#146]
```ink
VAR x = 0
VAR y = 0

// works
{ 
    - x == 0:
       Hi
    - x > 0:
        Hello
    - else:
        what's up
}

// fails
{ - x == 0:
       Hi
    - x > 0:
        Hello
    - else:
        what's up
}
```

**Comment by joethephish** [comment]
The failed example is actually a different style of conditional.

When you have a condition on the first line, it's in the "standard if statement" form or a "switch statement" form, and your leading `-` is actually being read as negate/subtract. You get an error on the middle condition since that form of conditional should either only have two branches (a simple if/else), or it should be a switch statement. For example:

```
{ x > 0:
    Greater than zero.
- else:
    Not greater than zero.
}
```

or the switch-statement form:

```
{ x:
    - 0: zero
    - 1: one
    - 2: two
    - else: something else
}
```

Hope this helps!

**Comment by wilg** [comment]
Hmm... thanks for taking a look! This is a pretty weird sharp edge. The latter form is [not documented](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#3-conditional-blocks-ifelse) as far as I can tell.

It also violates the assertion in the docs that:

> (Note, as with everything else, the white-space is purely for readability and has no syntactic meaning.)

Additionally, it doesn't do what I expect in this example (though maybe I'm misunderstanding this feature):

```ink
VAR x = 2

{ x:
    - 0: zero
    - 1 == 1: should return this (or error)
    - 2: WAT
    - else: something else
}
```

It seems to me that a switch statement like your example and an if/else if/else like my example should potentially have distinct syntax both for the compiler and humans' sake.

**Comment by joningold** [comment]
You might well be right about the lack of documentation - I should get onto that.  

On the latter example, the flow prints the WAT line because x doesn't equal 0 (first case), or true (the result of the evaluating the second case), but it does equal 2 (the third case).

The way I usually think about it is that any multiline conditional is basically, actually, a switch statement, but where the value being switched for is "true" by default. So:

```
{ 
 - false: nope
 - true: yup
 - else: still nope
}
```

is really doing 

```
{ true: // go with first case that matches this
   - false: nope 
   - true: yup 
   - else: still nope
}
```

**Comment by joethephish** [comment]
In your `1 == 1` case above, there are a couple of things going on. Firstly, we don't have true booleans internally (it's C-style), so `1 == 1` evaluates to true, which is actually just `1`. So in your example, it's checking whether `x == (1 == 1)` => `x == 1` => `false` (or more accurately, zero!)
