### ISSUE TITLE
Including images

### ISSUE THREAD

**Issue by markcmarino** [inkle/ink#153]
Is it possible to include images yet using ink? That would be extremely helpful.

**Comment by joethephish** [comment]
Ink's philosophy is to be a general purpose interactive text language that can be used in different contexts: e.g. 3d game engines or on the web. For that reason, it's designed to be barebones in the type of content it handles. It's up to the individual developer to implement a simple custom parser for the content they want.

For example, if you were targeting the web and exporting from Inky, you might invent this syntax:

```
What do you think of my picture?
IMAGE: landscape.jpg
* It's beautiful!
* Show me another
```

...and then modify the JavaScript source to parse a line of content that leads with `IMAGE:`, and convert it into an `<img>` tag.

**Comment by ElanaE** [comment]
Could you perhaps explain to me what the last part means in detail ("...and then modify...") - or point me into the direction of an article/video? I would love to be able to add a simple page divider since I frequently give the reader instructions which are ideally separated from the rest of the story. 

I was first thinking that images might be integrated with tags, since the tutorial "Running Your Ink" mentions that tags can be used to refer to filenames, but it didn't work the way I thought it would, so now I'm quite sure I don't actually understand how to use tags at all lol.

**Comment by joethephish** [comment]
So, in your export for web, open up main.js and replace the contents of the while loop in `continueStory()` with this:

```
// Get ink to generate the next paragraph
var paragraphText = story.Continue();

var htmlElement;
if( paragraphText.trim() == "DIVIDER" ) {
    // Create a horizontal rule tag
    htmlElement = document.createElement('hr');
} else {
    // Create paragraph element
    htmlElement = document.createElement('p');
    htmlElement.innerHTML = paragraphText;
}

storyContainer.appendChild(htmlElement);

// Fade in paragraph after a short delay
showAfter(delay, htmlElement);

delay += 200.0;
```

As you can see, it simply checks for the text "DIVIDER", and instead of creating a `<p>` HTML tag, it creates a `<hr>` tag (horizontal rule) instead. Obviously, you could use text other than "DIVIDER" instead, although ink uses up quite a lot of the syntax you might want to use, so you can't use, say, `====` or `----` unfortunately.

**Comment by ElanaE** [comment]
Not quite sure what this means. Sorry, but aside from basic html and now also enough knowledge of ink to create a Choose Your Own Adventure type story, this is all new territory for me.
Would this then allow me to integrate an image within the main .ink file the way you wrote above (IMAGE: DIVIDER.jpg), as in, refer to that file which would be included in the final zip folder...? Or would I use a tag (# DIVIDER) instead?

**Comment by jeremydouglass** [comment]
Worth noting that since at least Inky 0.10.0 / Ink 0.8.2, the `#IMAGE: myfile.png` line will include an inline image -- in export for web only, not visible in the Inky or Quill preview.

For a rundown, see:

https://www.youtube.com/watch?v=QZW4WDCfCKk
