### ISSUE TITLE
Some thoughts and comments

### ISSUE THREAD

**Issue by micabytes** [inkle/ink#17]
Writing here, for lack of any better persistent forum for discussion (chat has the problem that there is no history for guests, thus limiting the discussion to only those who happen to be present at the time of the discussion).

I have to say that the more I study Ink, the more I like it. I have some preferences that are at odds with what you've done (already mentioned), but I really like the expressiveness and succinctness of the script. I am particularly enthused by Weaves and the Knot = Function approach. These solve issues I've struggled with myself, and my own solutions are nowhere near as elegant.

Tempted to take my existing script engine, and making it Ink compatible. Probably keeping it in Java, although I'm rather keen on Kotlin and Scala at the moment. But Java is native to Android, and will also work for a web app (e.g., using the awesome [Play Framework](https://www.playframework.com/)). Have other things I need to finish up first, but it's definitely something that I could see a use for myself. We'll see how much time I have.

Some thoughts:

1. I'm not so worried about the JSON format, but I hope the script syntax and semantics wouldn't be something that would change very much in the near future (other than to add functionality). Otherwise it would be rather hard for people to start using Ink for anything serious.

2. Some things need to be specced a bit more rigorously. The thing I've noticed right now is the if-then and switch. The text claims that white space doesn't matter, but it's not obvious that this is the case (unless white space = only horizontal white space).

For instance, is:
`{     - x > 0:      ~ y = x - 1     - else:          ~ y = x + 1 }
`
The same  as:
```
{
    - x > 0: 
        ~ y = x - 1
    - else: 
        ~ y = x + 1
}
```
Or for that matter:
```
{  - x > 0: 
        ~ y = x - 1
    - else: 
        ~ y = x + 1 }
```
Haven't had the time to get this up and running on my Win PC yet, but whether it's only the middle one that is valid or all three are valid, I'd suggest that this is clarified in the docs. These kind of errors suck having to debug (one of my collaborators ran into something like this not long ago).

3. In general, some test specs would be useful. Understand why you haven't added anything substantial there, especially as you say the specs are still being evolved, but  a thing to keep in mind. It will make things much easier for people who wish to work on new runtimes/implementations.

4. One thing that I think is missing in the repo right now, is a good example Ink script. E.g., you Adventure of the Musgrave Ritual in Ink script and might as well throw in Cloak of Darkness as well. At least in my experience working with OSS, one always wants to make the threshold for adoption/interest as low as possible, and it really doesn't get much lower than saying "here, run this program on this script and see what happens".

Just my 25 cents.

Best of luck at GDC, btw. Hope the Ink talk will be made available; would love to watch it.

**Comment by joethephish** [comment]
Thanks, all good comments. To answer each in turn:

The overall syntax of ink itself is unlikely to change substantially now. We may *add* features further down the line and tweak small things, but otherwise, it can be considered reasonably stable.

The precision of the spec is definitely still really loose, as you say. In fact, many examples of syntax uses, including the ones you mention, aren't really ones that we've particularly considered up until now, since we've only used ink internally in our own "house style" so haven't pushed the boundaries of what is or should be possible. So right now it's really down to how the parser was implemented. Whether we'll *ever* have time ourselves to be very rigorous about speccing out this kind of thing is another matter - our primary focus is on building our own games. We'll do what we can to maintain the repo and will arbitrate decisions on the syntax specifics though, if someone wants to start a spec doc?

(Note that in your example above, tilda syntax can't be used inline (and there's an error message that's clear about that.)

Whitespace in ink is *hard* to get right. We have many constructs that can be combined and composed in various ways, and there are hundreds of permutations to consider. But we're doing our best to keep it as consistent as possible.

Definitely hear you on the example ink stories - it's something that we're working on, and should have something to show soon.

**Comment by micabytes** [comment]
Totally understand the need to focus on your games; it's what pays the bills, after all. A good test spec would probably be useful to develop, though; especially if people start developing more engines/parsers in other languages.

Incidentally, with mono now working I can see that the conditional syntax in 2 and 3 work fine. 1 doesn't (as you noted). Interesting.

I've seen you mention the Whitespace thing a couple of places, but not quite sure I understand the problem properly. Perhaps when you have some time after GDC, you could provide some examples of how things go wrong; the "hive mind" might be able to think up some solutions that aren't obvious to you.

**Comment by joethephish** [comment]
There is currently a set of 91 tests... though I'm sure they're far from exhaustive. You might want to take a look in `tests/Test.cs`. I'm not an expert on unit tests or specs though, so I'd be interested in feedback.

**Comment by micabytes** [comment]
Ugh. You know, I browsed through the tests directory and looked at the ink samples, but completely missed the cs file. /facepalm

In terms of test specs, I'm mostly thinking along the lines of [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development). Not sure what exists for C#, but with a good BDD test framework (I'm personally partial to Specs2 in Scala), you essentially end up with the tests being the specification. The benefit is that one avoids the disconnect between specs and tests that one can easily get as a project evolves; if it isn't tested, it isn't specced. 

I've pretty much decided to take a stab at Ink in Java when I get a little time, so I can take a brief look at that then. If I do manage to get something working for my own use, I'd probably knock out a player app for Android (and maybe web) as well, since it would be relatively little added work.
