### ISSUE TITLE
ChoosePathString with parameters

### ISSUE THREAD

**Issue by Flip120** [inkle/ink#187]
Hello I want to know if it's possible to use the function **ChoosePathString** from Unity API with parameters for knots.
For example something like that:

`_story.ChoosePathString("knotName", "intParam", "stringParam");`

**Comment by joethephish** [comment]
Apologies, not right now!

We did recently add the ability to call a `function` knot where you can pass parameters, although it immediately returns, since it's a function rather than "the main story flow". See this function on the story:

`public object EvaluateFunction (string functionName, params object [] arguments)`

And this one, if your function generates text as a side effect:

`public object EvaluateFunction (string functionName, out string textOutput, params object [] arguments)`

**Comment by Flip120** [comment]
Okay, thanks for the quick reply, these functions are at this moment enough for that I wanna to do.
