### ISSUE TITLE
Check if Knot or Stitch exists

### ISSUE THREAD

**Issue by joaorequiao** [inkle/ink#189]
Is there a way to check if a specific knot or stitch exists in the story? For example:

`If(story.CheckStitch("MyKnot.myStitch"))`
`       story.ChoosePathString("MyKnot.myStitch);`
`else`
`       story.ChoosePathString("MyKnot.defaultAnswer");`

Thanks in advance! #

**Comment by joethephish** [comment]
Official answer: Not right now, no, sorry.

HORRENDOUS HACK ALERT: Not any better than using try/catch, but you can use `public bool HasFunction (string functionName)`, since right now it returns true for knots and stitches as well as for functions.

**Comment by joaorequiao** [comment]
The horrendous hack will have to do then...!

Thank you for the answer Joe!

**Comment by nczaja** [comment]
Hey there,
I happily came across this horrendous hack from four years ago, and it doesn't seem to work for me... Is it me, or has it been eliminated for being horrendous? If so: Are there any alternatives, be they horrendous or wholesome?
Any help very much appreciated!

**Comment by joethephish** [comment]
Hmm, should work! Is it for a knot or a stitch?

**Comment by nczaja** [comment]
Oh, hey, you're quick! It's for a stitch, actually.

**Comment by joethephish** [comment]
are you doing it like this? `story.HasFunction("knotName.stitchName");`?

**Comment by nczaja** [comment]
Kinda. The string for the stitch name to check for is generated dynamically, like so:
`story.HasFunction(currentLocationName + "_to_" + target.gameObject.name + ".day_"+ travelDayNumber.ToString())`
When I use that same composite string with ChoosePathString to jump to the stitch in question, it works fine.

**Comment by joethephish** [comment]
Oh sorry, yes. Just looking through the code, I realise I refactored it a while back for efficiency reasons and this will no longer work for stitches.

I should be able to give you a solution if you're including the ink runtime code directly in your project (so that you can use `internal` stuff rather than purely `public` stuff? And/or if you want to edit the source of ink's Story.cs directly?

**Comment by nczaja** [comment]
Oh ok, that explains it - so it wasn't me getting stuff wrong, that's worth something.
Internal stuff sounds exiting, let's do away with the boring public stuff! 
I'll gladly give it a try if it's not too much bother for you (and not too complex for me, as I'm a complete coding noob).

**Comment by joethephish** [comment]
In that case you should be able to do the following:

`bool hasKnotOrStitch = story.ContentAtPath(new Ink.Runtime.Path("knotName.stitchName")).correctObj != null;`

If the C# compiler tells you that you can't access ContentAtPath since it's internal, then it's probably because you're using the latest ink unity integration plugin that has an assembly definition file, preventing you from accessing internal stuff. You should (I think) be able to just remove the .asmdef file and everything should work...!

**Comment by nczaja** [comment]
Brilliant! I'll try that out.
Thanks for being super helpful!
You can say a lot about the internet these days, but it _is_ kind of a Golden Age for getting instant help with your newbie coding questions, and directly from the co-founder of a studio you deeply admire, no less.

**Comment by joethephish** [comment]
Hah, thanks for the kind words. But I'm pretty awful at keeping up with the posts on here, you're lucky you caught me on a good day! Good luck :)

**Comment by nczaja** [comment]
Final heads up: Works like a charm. 
Thanks again! 
(...and I just joined the inkle discord, which probably is a more fitting place to ask questions like that in the future).

**Comment by klootas** [comment]
Nice! There are some visibility issues here though, perhaps the internal types could be made public, or perhaps this could be added to Story:

public bool CheckSectionExists(string name)
{
    return ContentAtPath(new Ink.Runtime.Path(name)).correctObj != null;
}

Thanks a bunch for the solution!
