### ISSUE TITLE
Bug: Setting global variable from c# can set local variables unexpectedly

### ISSUE THREAD

**Issue by joningold** [inkle/ink#193]
This is a highly specific bug, but took me a long time to find!

if on the game side you use 

`story.variablesState["variable_name"]  = some_value`

and then also have 

`=== function some_function(variable_name)  ===`

with variable_name not actually a global variable at all, then when that function is called it will use the value "some_value", not the value passed in by the function call.

Presumably what should be done here is the global variable should be set via a method that validates that the global is indeed a global, rather than pushing into the dictionary directly?

**Comment by joethephish** [comment]
Hrm, yeah. I guess I've always try to take a flexible approach to variables in ink, JavaScript style, so there aren't aren't so many checks internally. But given that we already enforce variables to be defined up front in the compiler, this does make sense.

Perhaps only tangentially related, but the question of how flexible it is internally affects how will the game can cope with the story changing with an existing serialised save state (as we were chatting about the other day). Since if you add/remove variables between story versions, then it might not cope so well unless it tries to be a bit forgiving...

**Comment by joningold** [comment]
Yeah, in the current prototype when we load old data into a new story it
tends to crash as it can't find a newly added variable!

Jon

**Comment by joethephish** [comment]
Created a new issue about that problem, since it's separate problem really: #195

**Comment by joethephish** [comment]
Fixed in f24f520abdbf0ad4c60f2b420e229e1d1b6e483d.
