### ISSUE TITLE
Localization in Ink + Unity

### ISSUE THREAD

**Issue by Mitinuru** [inkle/ink#196]
Hi,

What is the best way to do localization for ink stories in Unity? 

I can see three strange ways to do so:
1. run a separate json file for each language
    "-" a mess of editing several files if story ever changes
2. include tags instead of text into the text file that Unity later can substitute with localized text
    "-" no idea how to actually implement it
3. use {language.english: text_in_english| language.french: text_in_french} for every bit of text in the story
    "-" a great mess of a ink file...

Nadya

**Comment by joethephish** [comment]
There have been a few discussions on this topic. For example, see #98 and #89. My personal preference right now is option 1, with the assumption that there is a certain date where you'd (mostly!) lock down future changes, or at least put restrictions on so that updating the translations is as straightforward as possible.

It also depends a lot on exactly how branchy your content is - localisation on Sorcery! and 80 Days is all but impossible because of variations in the content on a word-by-word basis. But if your content isn't written that way, then it's more feasible.

**Comment by Mitinuru** [comment]
Thank you for advice!

**Comment by Syjgin** [comment]
https://johnnemann.medium.com/localizing-ink-with-unity-42a4cf3590f3 more detailed description of tag approach. But it's still looks like a dirty hack
