### ISSUE TITLE
Querying Current Knot

### ISSUE THREAD

**Issue by zBohn** [inkle/ink#198]
Is there anyway for an external codebase (I'm working in C# in Unity) to query or determine the current Knot that the Story is in?

I would like to be able to identify specific knots to use them as triggers for audio changes.
Something like:
if(Story.CurrentKnot == "===1D===")

Reading through the documentation it appears that a Path contains information about a Knot, but State.CurrentPath is an internal variable.

**Comment by y-lohse** [comment]
I don't know the answer to your question, but you could use the new tag feature for that :-)

**Comment by y-lohse** [comment]
I meant using tags to trigger the audio changes instead of looking at the current knot.

**Comment by zBohn** [comment]
Thanks @y-lohse . I'll give the tags system a shot. Seems like a good workaround. Will just create unique tags per Knot that I want to have trigger the audio. 

@joethephish Exposing CurrentPath on State would be a nice future addition. I can see a few other ways I may want to have the .INK file trigger something on the code side based on the KNOT.

**Comment by joethephish** [comment]
Hmm, after looking into it, I realised it doesn't make sense to expose `currentPath` since it's only non-null in the middle of evaluation. When it's finished evaluating a single turn, evaluation completes so it becomes null.

However, I've added a property to the `Choice` class: `sourcePath`. This will give the exact location in the story where your choice was defined, which should be roughly equivalent to what you're asking for.

(Done in commit 8760d71c1a8da22d84c8f4e6bcc4bb171a895714, will be in next release.)
