### ISSUE TITLE
Bug: Gather point not being hit

### ISSUE THREAD

**Issue by joningold** [inkle/ink#205]
```
{ false:
    + [OPTION NOT EVEN SHOWN]  -> END
}

DOES SHOW THIS
//  - -  (uncomment_to_fix)

- SHOULD SHOW THIS -> END
```

**Comment by joethephish** [comment]
After some investigation, it turns out this isn't a bug but intended behaviour. A long time ago we a decision that it should behave exactly like this. Take the following simple example:

```
- What ice cream do you prefer?
    * Vanilla
    * Chocolate
- That's my favourite too!
```

The writer always expects the flow to pause to give the player choices. If however, the writer puts the choices behind conditionals:

```
- What ice cream do you prefer?
    {vanilla_available:
        * Vanilla
    }
    {chocolate_available:
        * Chocolate
    }
- That's my favourite too!
```

The behaviour needs to stay consistent. Namely, if `vanilla_available` and `chocolate_available` are both false, you don't want the flow to immediately drop into "That's my favourite too!" since it's semantically changing the core behaviour. Instead, you want it to run out of flow, since really there should've been another option that *was* available. A workaround therefore is to include a default fallback option:

```
- What ice cream do you prefer?
    {vanilla_available:
        * Vanilla
    }
    {chocolate_available:
        * Chocolate
    }
    * ->
- That's my favourite too!
```
