### ISSUE TITLE
Visual Documentation of Stories

### ISSUE THREAD

**Issue by bateramos** [inkle/ink#22]
Hello, 
When I has creating my stories, I felt the need to some sort of visual documentation of the decision path the this stories could take. So I use Astah UML (Activity Diagram) to make this.
Was someone uses another software to make this or has some tips to give?
![diagram1](https://cloud.githubusercontent.com/assets/1529658/13821653/3f0b5eee-eb81-11e5-8f24-92809fd5d280.png)

**Comment by rubereaglenest** [comment]
Well, you can use Twine for that and...

I found this script system that has some interesting tools. The script could export to some format, pdf, latex json twyne and the 

https://github.com/lifelike/gamebookformat

It is open source, so I think it could be a good idea make a fork or adaptation to feed in ink scripts and get a .dot file that could be feed to Graphviz to generate a flowchart image.

More information about .dot here:

https://en.wikipedia.org/wiki/DOT_(graph_description_language)

**Comment by micabytes** [comment]
I suspect you might see some issues trying to plot ink script for the general case, due to the "in text" diverts and advanced features like threading. If you stick to the basic elements, though, it might be OK.

Probably easier to go the other way around (from diagram to ink).

Crumbly Head Games has a commercial [gamebook authoring tool](http://www.crumblyheadgames.co.uk/). Doesn't support Ink though (at least not yet).

**Comment by rubereaglenest** [comment]
Yeah, you are right. I wonder what Inkle guys do with their stories, if the go the old "spread papers on the floor" way, or post-its on a white board, or some tool as the proposed ones, or a script to map their stories.

**Comment by joningold** [comment]
So, for our stories we do no mapping at all.

Ok, that's not *quite* true; we do make geographical maps of the physical
space that the player moves through; and that map roughly matches the "plot
map" of the game.

But we don't bother mapping the cause/effect and consequence graphs of
scenes. I've never found a reason to: ink tells me if I have loose ends to
fill out and in general, we try to write "scenes that can cope with being
read in any order at all" so we don't need to think about too hard about
what can come before what. Instead of making a graph, we index all the
"major events" by creating boolean VARs for them, and then make sure scenes
are robust against that index.

Then we play the game a lot to see if there are sections that feel too
short / throwaway. I've never found a flow-chart to be a good measure of
that, really - and I find graphs have loads of negatives; they hugely limit
how much variability you can write because you can only draw so many
branches and get them to fit, and they make quite simple structures look
complex, which is the wrong way round. (Hence weave format in ink: it makes
complex structures look simple.)

So for me, part of the reason ink exists is that, I find, you write better
interactive stories when you stop trying to control the structure of the
story graph, and concentrate instead on writing good content that strings
itself together.
