### ISSUE TITLE
How to create a Clear page/New page?

### ISSUE THREAD

**Issue by freejsf** [inkle/ink#221]
Hi,

first of all, thanks a ton for sharing this. This is an amazing tool and seems to have just the right amount of simplicity and complexity that I need for my projects.
My apologies if this question has been answered elsewhere, but I have been looking for an hour now and checked out the exampmpes and can't find it:
Is there a way to create a new page or clear page after a block or choice? While I like the flow of the continues text, from time to time I would like to give readers a fresh page for dramatic reasons.
Is there a markup command or what is the standard way of doing so?

**Comment by joningold** [comment]
Hey!

The answer is no, because ink is really intended to be the middle part of a
project and not an end to end solution. So assuming you're using the web
export from inky, you could:
- export the project
- hack the JS file so that when the story encounters a single option called
CLEAR it doesn't display it, but instead waits for a click and then clears
the screen
- use
* CLEAR
In your script
- and then just remember to use "export story.js" not "export for web" when
you update your game content (as doing a full export will overwrite your
hacks)

... and of course this is basically how you could achieve any other effect
you want.

Jon

**Comment by freejsf** [comment]
hey Jon,

thank you, this is helpful. I will do it this way then.

j
