### ISSUE TITLE
Accessing knot from code 

### ISSUE THREAD

**Issue by fares57** [inkle/ink#231]
For example. 

If (knot we are in now is blahblahblah) {
play that sound etc etc
}

I've used variableobserver  but I dont want to use vars. I d'have to do double work, adding a new var under each knot. 

story.state.VisitCountAtPathString also seems a plausible choice but then, i d have to construct a whole method to make sure the count got up which means i am in this knot now blah blah....

Can't i fo directly with knots? Thank you very much.

**Comment by ashleytwo** [comment]
Yeah this would be really useful.

I've found a hacky way of doing it, but it's not ideal.  Even just an inbuilt function which returns the name of the current knot/path as a string would be sufficient for myself.

What I've done, for anyone that is interested, is under the name of the knot in Ink added the following:

`#currentknot:[knot_name]`
e.g. #currentknot:first_knot
`
Then in Unity I'm already adding all current tags to a string list and then it looks out for 'currentknot' and assigns the value of that to a string variable (which I've named currentKnot) using Substring to extract the bit I want.

`
for (int i = 0; i < _inkStory.currentTags.Count; i++) {
				tags.Add (_inkStory.currentTags[i]);
				if (_inkStory.currentTags [i].StartsWith ("currentknot")) {
					currentKnot = _inkStory.currentTags [i].Substring ((_inkStory.currentTags [i].IndexOf (':') + 1));
				}
			}
`

The substring looks for anything after the character : +1 (i.e. it won't include the semi-colon itself).

I've also created a variable for the previous knot which I'm not sure if it will be useful, but threw it in.  It's just a minor change to the if statement above.

`
if (_inkStory.currentTags [i].StartsWith ("currentknot")) {
					if (currentKnot != _inkStory.currentTags [i].Substring ((_inkStory.currentTags [i].IndexOf (':') + 1))) {
						previousKnot = currentKnot;
						currentKnot = _inkStory.currentTags [i].Substring ((_inkStory.currentTags [i].IndexOf (':') + 1));
					}
				}
`

At least this way I can then use the inbuilt TagsForContentAtPath and state.VisitCountAtPathString to look at the current knot automatically rather than having to manually type it in to the c# code (although of course you need to add it as a tag within the Ink story, which is why it would be preferable if something like this was automatic).

**Comment by facelesspanda** [comment]
why don't you use externals? Or just an `ambient: sound-name` in your script? ( I personally prefer the latter because it doesn't rely on the game engine, it's just about parsing)

Ink exists to separate script from game logic and have separate workflows. If in game logic you need critical script info (like the knot name), then the whole purpose of Ink goes to trash.

Use your script to declare this kind of stuff. And parse the script to handle them from game logic.

**Comment by y-lohse** [comment]
Maybe this can help you : https://github.com/inkle/ink/issues/198#issuecomment-252895961

**Comment by fares57** [comment]
yes but I am completely noob in github and I don't know to handle this haha!

**Comment by y-lohse** [comment]
I think it's already in the latest build, so you could do something like this:

```
Choice choice = _inkStory.currentChoices [0];
if (choice.sourcePath == "haunted_mansion.corridor"){
  //play the organ sound
}
```

**Comment by fares57** [comment]
but I had only the integration plugin downloaded. Now I downloaded the full stuff , put it in the plugins folder of the assets folder of my project and now I can "see" all the classes and methods . I can now implement it I guess. Did I so the "right" way? :p

**Comment by y-lohse** [comment]
I... think? That's more a Unity question, I'm not really qualified to answer that :-)

**Comment by fares57** [comment]
No, I didn't. It seems I am full of compiler errors now. Tests.cs , then others.

**Comment by ashleytwo** [comment]
Wasn't aware of the current knot, thanks for that!

Out of curiosity, what is the whole string it's returning?  Obviously there's the name of the path, but I'm getting it followed by three period delimited numbers and I can't figure out what they are.  I can tell the second is affected by the choice given, but can't see a direct relation.  

Thanks!

**Comment by fares57** [comment]
I wish I could tell, but I still try to figure my way out of Github :p 
I imported the integration from the store but it doesn't contain the Runtime classes as mentioned in the description!! 

If I try to copy the runtime folder from here to my assets/plugin/ink folder of my project, I just get the error :
	The type 'Story' exists in both 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ink-engine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'	InkleStory.CSharp.Editor.Plugins	C:\Users\...\Documents\InkleStory\Assets\Plugins\Ink\Editor\Player Window\InkPlayerWindow.cs	17	Active

I am so lost!

**Comment by fares57** [comment]
I give:
Choice choice = story.currentChoices[0];
        Debug.Log(choice.pathStringOnChoice.ToString());
And I get:
'^'

I don't understand this. My knots are in English ( === blahblah ===)

**Comment by ashleytwo** [comment]
The earlier recommendation was choice.sourcePath rather than pathStringOnchoice.  The former worked for me last night.

**Comment by ashleytwo** [comment]
From what I recall I downloaded the package from here and then imported the package into Unity.  I can't recall doing any more than that and I also can't remember having any issues.

Maybe worth starting a new project and trying importing it again?

**Comment by fares57** [comment]
I get a conflict. I just copy paste the runtime folder from here to the project. 

I update to last version of Unity now. They updated the Asset package in the store today and demands the latest version. Maybe it ll get fixed, i ll see in a while. ;)

**Comment by fares57** [comment]
Seems it was updating or something. I imported again, from store, after updating Unity and I have the full package now including all the runtime classes. ;)
