### ISSUE TITLE
Inklecate/Mac issue: takes up 99% CPU

### ISSUE THREAD

**Issue by DannyHoman** [inkle/ink#252]
Hey all:

Inklecate seems to take 99% of my 2012 macbook pro's CPU (when viewed in activity monitor). Once I quit Inky, inklecate remains active unless I force quit. Any idea what's going on/how to fix? Thanks!

**Comment by joethephish** [comment]
Hmm, this used to be a common problem, but a while ago I made some fixes that tidied this up and haven't seen it since. Shame it hear that it's rearing its ugly head again!

Is it happening consistently/frequently or not? Any other information you can give me about circumstances would help!

**Comment by DannyHoman** [comment]
Hey -- attached a screenshot. Running 7.0 of Inky. Inklecate issue only occurs when I've been using Inky for more than approximately 10 minutes. Let me know if there's something I should do on my side. Mac's got a 2.3 GHz Intel Core i5, 8GB Memory, and is running 10.11.6. Thanks!

![screen shot 2017-01-12 at 8 51 06 am](https://cloud.githubusercontent.com/assets/1790539/21894332/68002152-d8a4-11e6-96be-cce8add12717.png)

**Comment by drewsonne** [comment]
@joethephish I just noticed this as well. Can I ask what were the commits/PR's you could reference which fixed the previous problem?

**Comment by joethephish** [comment]
So, there are a couple of things going wrong here, and it's related to the way that Inky's node scripts communicate with the C#-built inklecate binary (the ink compiler). The compiler runs stories in "play mode", meaning that they're played on the command line and Inky parses the output.

There are two bugs which are working in conjunction:

1. When running the compiler in play mode, it uses .NET's `Console.ReadLine()` to wait for input from the user - i.e. to make a choice. Depending on the environment, this seems to either correctly wait for input, or immediately return null (because there's no more input - it's the "end of the stream").

    **To reproduce this**: run inklecate through Xamarin by opening ink.sln. Choose the inklecate target in the tests configuration and simply add `* hello` to `test.ink`. If you run, it should launch an external terminal window (on Mac), and works fine. When you make the choice, it'll exit successfully. However, if you change run options to not use an external terminal window (right click inklecate -> Options -> Run -> Default -> Run on external console). Then when you run, `ReadLine` always executes immediately and returns null.

2. If Inky somehow "loses communication" with a running instance of the compiler, then we see this behaviour - the process doesn't exit, and instead stays alive, with `ReadLine` returning null, and with the output being spamming like a fire-hose with `?> Unexpected input. Type 'help' or a choice number.`, which is why the CPU % goes way up.

The communication between Inky and the compiler all happens in `main-process/inklecate.js`. Inky spins up an instance of the compiler each time it wants to refresh the ink that the user has written and plays it on the command line, with `inklecate.js` parsing the output. Each of these sessions is stored an entry in `sessions` (see line 33 of inklecate.js). Previously my logic for adding and removing the sessions was faulty - I think I was getting the session IDs wrong, I can't remember exactly! But it would mean that sessions (and therefore instances of the inklecate process) could get orphaned.

This happens especially often if Inky crashes for whatever - the compiler process stays alive but loses communication with Inky, and spams output.

---

...in the process of investigating and writing up this comment, I think I may have a solution! My guess is that if `ReadLine()` returns null, we should really be exiting the process - since it's up to the environment to "want to pause to allow user input". If the environment isn't doing that, it's clearly not interested in receiving user input for whatever reason. I guess Xamarin's built-in console doesn't handle that correctly, or isn't designed for testing CLI apps, or there's something else I'm missing?

Either way, if we fix that, I reckon that even if Inky crashes, the processes should be cleaned up correctly...

**Comment by joethephish** [comment]
Have pushed a possible fix in commit 32fa48a251826d82b9e4e36b04f147bf577a05e5, will pull it into the next build of Inky.
