### ISSUE TITLE
External Functions now evaluated twice when sandwiched between content

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#253]
We recently upgraded from 0.4.1 to 0.7 and noticed that the behavior of external function calls has changed when its sandwiched between two lines. We've skipped quite a few updates so I don't yet know when this cropped up, but I'll update the issue when I track it down.

External functions are now evaluated once, for the line they appear above, and once, for the line they appear below. 

Below is a small ink that illustrates the behavior. During my test the function log is bound using the API to Unity's Debug.Log(). On version 0.7 "I dig it!" is printed to the console twice. Once when the line "theres some gold in my purse" is shown and once again when "Now isn't that nice" is show. In 0.4.1, 

The value of gold is, correctly, 10 by the end of the story. So I'm guessing that this behavior is not expected.

```
INCLUDE ../Inc/Functions.ink

VAR gold = 0

===function give_gold(x)==
~ gold = gold + x
~ log("i dig it!")

===GoldTest===
Here young man, I have a reward for you
There's some gold in my purse
~give_gold(10)
Now isn't that nice?
{gold}
->END
```

-Jonathan

**Comment by nullObjectPtr** [comment]
Looks like the bug was introduced in version 0.6.4

**Comment by joethephish** [comment]
So, I know this is weird, but I'm afraid it's expected. It's all to do with glue.

Quick recap of how glue works:

```
Hello 
<> world.
```

...prints `Hello world.` - i.e. it joins the lines together. Now, under normal circumstances, if you do:

```
Hello world.
~ f()
Another line.
```

It will do what you expect (if ink is all internal - as you said - your gold count is fine). But the reason that you get the function called twice is that it has to look forward to see if there's going to be glue in the future. e.g., you *might* have a situation like this:

```
Hello 
~ f()
<> world
```

So, when the ink engine sees the newline after `Hello`, it saves a "checkpoint" (the entire ink state), and continues evaluating. If it sees some glue, then it deletes the newline and continues evaluating as normal. But, if it sees normal text content, then it rewinds to the checkpoint, where it saw the last newline.

Then on your *next* `Continue()` call, `f()` will be called again, "for real" this time.

Internal state is fine with this, since it all gets rewound correctly. If you use a variable observer, it also works correctly, since it only checks state changes after a `Continue()` call, to ensure the value has really changed, and to ensure you don't get lots of calls if the variable changes multiple times.

But I'm afraid this is one of the disadvantages of using externals. To be honest, I do wonder whether we ought to be more explicit about discouraging the use of external functions for certain purposes like this. They're good for performing complex calculations that you wouldn't want to do in ink, and good for grabbing state from the game, but in general we'd recommend using variable observers, tags or just plain old text where possible.

And the reason this has changed in 0.6.4? Previously, the game would save a checkpoint of state *for every single compiled ink instruction* until it saw glue or proper text content. So if your internal ink `f()` ran for more than a few instructions, it would be horribly slowly, and it was also semantically not really correct, since it would actually fun `f()` as part of the first line, when really it should've stopped at the newline.

Sorry, I realise that probably isn't what you want to hear!

**Comment by joningold** [comment]
TODO: We need to add to documentation to say "External Functions should only ever *read* game-state / do computations for the ink's benefit; they should never be used to *set* game-state and/or produce a game-side effect."

For game-side effects we recommend using tags; for state-setting we recommend variable observers. (We also sometimes use "text in a particular format" as well.)

**Comment by taylorhadden** [comment]
So the crux of it is that you don't support function calls with side effects.

This is incredibly disappointing. I can't recommend enough that this issue is somehow resolved. This is extremely unintuitive functionality and, in my opinion, means that how the glue feature is implemented should be revisited.

This seriously calls into question our decision to use Inkle.

**Comment by joethephish** [comment]
Just added some notes about this [to the documentation](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#important-notes-on-the-usage-of-external-functions).

**Comment by joethephish** [comment]
As of 342e474315499dac310a5c4529c4a569617b3cd7, this is now fixed. The new default behaviour is that `EXTERNAL` functions will only be called once. However, at binding time you can choose to get the old behaviour that should only be used with pure functions. To do so, use the following code:

    story.BindExternalFunction("myAction", () => callCount++, lookaheadSafe:true);

**Comment by joethephish** [comment]
Added this to the documentation: https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#actions--vs-pure-functions

**Comment by micabytes** [comment]
Brilliant.  This has definitely been one of the issues I've had with using Ink. Implementing instructions as you suggested previously works, of course, but remains a problem when using functions to inspect game state changed by those instructions. Thanks a lot for doing this.

Also, congrats on the grant.

**Comment by DrewRWx** [comment]
I've also been watching this issue for a while for a Slack bot project I want to revive. You've got a really happy Patreon supporter on you hands!

Congrats on the release!

**Comment by joethephish** [comment]
Glad it’s helpful for you!
