### ISSUE TITLE
Choices inside shuffles don't becomes weaves

### ISSUE THREAD

**Issue by joningold** [inkle/ink#258]
```
{ shuffle:
-   *   a choice 
        Its response 
}
```

produces the output 

It's response 
1) a choice

which is not as intended.

**Comment by joethephish** [comment]
Fixed in 664658a3056ec545a93ae48a8e56188ed3016e69.

I think perhaps I assumed that sequences that contained weaves shouldn't be possible, because of the collision in syntax with the `-` character. But obviously they should be able to contain choices! (Choices were obviously being parsed before, they just weren't getting weavified.)
