### ISSUE TITLE
Parse storyfiles automatically after Ink compiling

### ISSUE THREAD

**Issue by ZephyrRaine** [inkle/ink#261]
Hello there!

I tried to find this in source code but haven't figured the best way to know the InkLibrary has been updated (when importing new .ink file) and how to automatically parse the included files after Ink Engine has done its work. I thought of using AssetPostprocessor like the AutoCompiler but I'm not sure about how to make sure they execute in the right order.

Thanks in advance!

**Comment by tomkail** [comment]
Hi! Can I suggest using the static OnCompileInk event in InkCompiler? It won't tell you when a file is added to the library (since that process, along with the library is supposed to be somewhat invisible), but it will tell you when your edited stories are ready to be used, which I imagine is what you're looking for?

**Comment by ZephyrRaine** [comment]
Thanks I'll try that :)
