### ISSUE TITLE
[Question] Validating tags & custom strings

### ISSUE THREAD

**Issue by cduquesne** [inkle/ink#270]
Hi ! 

I have questions about the extensive use of tags, or parsed text.
As they seem to be a recommended solution for many things (as mentioned by @joningold in #253), do you have best practices for validating these strings ( = making sure the values are accepted by the external engine) ? Is there something simpler than modify the parser itself ?

Thanks !

**Comment by joethephish** [comment]
We don't currently validate them other than at runtime.... we haven't had much of a problem with this so far, but perhaps because we use quite a simple format that's easy to "eyeball" for correctness?

If you are interested in hooking into the parser though, take a look at `Ink.IPlugin` - you can write a class that gets a call after the story is parsed, and after it's compiled. Though currently you have to compile your class into the compiler itself.

**Comment by cduquesne** [comment]
Ok thank you for the details !
