### ISSUE TITLE
Parsing knots and stitches

### ISSUE THREAD

**Issue by ZephyrRaine** [inkle/ink#274]
Hello, I'd like on loading the game or when ink files are reimported to parse all the stitches of a knot/ink file, in order to create associated game data. Is there anyway to do this properly?

**Comment by joethephish** [comment]
Sorry, not right now! I'd like to add metadata to the compiled ink file in future so that there's information about the available knots and stitches and their signature (if they take parameters etc), but right now there isn't an interface for it.

If you wanted to hack the ink source: The `Story`'s `mainContentContainer` has a dictionary that has keys for all the top level knots and functions - within the `Container` class, take a look at `namedOnlyContent` - the keys will be the names of the knots and functions. You'd just have to expose those names. However, this is a bit of a hack because we make no guarantee that that top level container's structure will remain the same, or that it will contain *only* knots and functions.

**Comment by ZephyrRaine** [comment]
Works like a charm! Many thanks as it allows making custom editors and overview very much easier, as it would be overkill to parse all files myself after ink's done it. 
![screen](http://i.imgur.com/XmmWsSz.png)
