### ISSUE TITLE
Inklecate compile chokes on any external function call

### ISSUE THREAD

**Issue by jjsonick** [inkle/ink#285]
So I'm consistently seeing inklecate crash during compile if my .ink file includes any external function call.  I'm using Unity 5.5.1f1 and the 0.7.1 UnityInkIntegration package.

I've made the simplest test of the issue using the example external function from RunningYourInk.   The ink file is just:

EXTERNAL multiply(x,y)

3 times 4 is {multiply(3, 4)}.

The error message is:

Unhandled error occurred compiling Ink file [InkFile: filePath=Assets/Ink/extFunctTest.ink]! Please report following error as a bug:

Unhandled Exception: System.TypeLoadException: Could not load type 'Ink.Runtime.InkList' from assembly 'ink-engine-runtime, Version=1.0.6219.30678, Culture=neutral, PublicKeyToken=null'.
   at Ink.Parsed.FunctionCall.GenerateIntoContainer(Container container)
   at Ink.Parsed.Expression.GenerateRuntimeObject()
   at Ink.Parsed.Object.get_runtimeObject()
   at Ink.Parsed.ContentList.GenerateRuntimeObject()
   at Ink.Parsed.Object.get_runtimeObject()
   at Ink.Parsed.Weave.GenerateRuntimeObject()
   at Ink.Parsed.Object.get_runtimeObject()
   at Ink.Parsed.FlowBase.GenerateRuntimeObject()
   at Ink.Parsed.Object.get_runtimeObject()
   at Ink.Parsed.Story.ExportRuntime(ErrorHandler errorHandler)
   at Ink.CommandLineTool.<CommandLineTool>c__AnonStorey1.<>m__3()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)

UnityEngine.Debug:LogError(Object)
Ink.UnityIntegration.InkCompiler:Delay() (at Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs:186)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

The bound multiply function is exactly the same as in the doc, and I placed it in the MonoBehaviour script where I handle everything _inkStory related, placed right after I initialize a new _inkStory (should the function be placed elsewhere?  Does it need additional C# setup from what the doc has?).

If I remove the {multiply(3, 4)}, inklecate compiles the .ink file without complaint, so it's definitely the call generating the crash.

I deleted Ink and reimported the package in my project just to make sure - same results.  (And compiled ink files are otherwise behaving normally in my project).

**Comment by joethephish** [comment]
Hrm, so I'm pretty surprised that external functions have anything to do with this error, I think it might be slightly by chance.

What's happened recently is that we've split in the inklecate.exe binary (which does the actual compilation from ink to json) into two: the main inklecate, and a DLL which it relies on (ink-engine-runtime.dll). What it sounds like is that the runtime DLL is out of date somehow - since it's complaining that it can't find "Ink.Runtime.InkList", which is part of the lists feature, which is fairly new (and the type name was recently updated).

Where did you download the unity integration package from? The Asset Store version can get out of date sometimes since it requires approval from Unity. Can you make sure you have the latest version from here: https://github.com/inkle/ink/releases (I just tested on a new test project and it worked for me.)

Here is the latest version of `ink-engine-runtime.dll`, that should sit next to `inklecate_win.exe` and `inklecate_mac` within the Inklecate folder:

[ink-engine-runtime.dll.zip](https://github.com/inkle/ink/files/844241/ink-engine-runtime.dll.zip)

...just to make sure that you definitely have the right version.

Can you also check that the following settings are all unchecked when you select the dll in Unity, since it needs to be available to the inklecate binary, but *not* imported into Unity itself:

![image](https://cloud.githubusercontent.com/assets/858967/23946097/f76ddc7e-0970-11e7-92de-792da00f8225.png)

**Comment by jjsonick** [comment]
I'm using the 0.7.1 unity integration package from Github, not the Asset Store.  Just to make sure, I replaced the ink-engine-runtime.dll with the one you provided above.  Same results.  The settings for ink-engine-runtime are all unchecked, just as in your screenshot above.

Are we both testing in the same Unity  version - 5.5.1f1?

I've done some additional testing: 

An .ink file with variables, choices, knots, diverts, and cycles will happily compile.

But if I add a 'normal' internal function call, it also crashes during compile. So, apparently any function call.

Also, I noticed the error messages include "Could not load type 'Ink.Runtime.InkListItem'...", so I tried removing the offending function, getting a working compile, and then adding a single LIST line, 'LIST kettleState = cold, boiling, recently_boiled' to the top of the .ink file.

Sure enough, it again crashes, with a similar error message: 

"Unhandled error occurred compiling Ink file [InkFile: filePath=Assets/InkFiles/extFunctTest.ink]! Please report following error as a bug:

Unhandled Exception: System.TypeLoadException: Could not load type 'Ink.Runtime.InkListItem' from assembly 'ink-engine-runtime, Version=1.0.6219.30678, Culture=neutral, PublicKeyToken=null'.
   at Ink.Parsed.ListDefinition.GenerateRuntimeObject()
   at Ink.Parsed.Object.get_runtimeObject()
   at Ink.Parsed.Story.ExportRuntime(ErrorHandler errorHandler)
   at Ink.CommandLineTool.<CommandLineTool>c__AnonStorey1.<>m__3()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)

UnityEngine.Debug:LogError(Object)
Ink.UnityIntegration.InkCompiler:Delay() (at Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs:186)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()"

So, an ink file with a LIST or a internal or external function call causes a compiler crash.  But an .ink file without any of those compiles fine.

Here is the exact Ink file I'm currently testing - it just has several example bits of code from the docs.  Currently the functions are commented out, and it crashes because of that LIST declaration.  But if I comment out the LIST declaration, it compiles without error:
http://pastebin.com/LXhBLDEf

**Comment by joethephish** [comment]
Very odd, it does suggest that somehow the version of inklecate (or dll) is *somehow* out of date in that it doesn't have the lists feature. Are you on Mac or Windows?

**Comment by jjsonick** [comment]
Windows - tested on both a Windows 7 and a Windows 10 machine with same result.

**Comment by joethephish** [comment]
Ahha, I think:

1. My build tools weren't updating the DLL correctly for the package and...
2. I forgot that the Mac version doesn't need the DLL, so it's only an issue on Windows.

Try this version of the dll? I believe it should work (it's a slightly larger file than the last one I uploaded, so I think finally this should be the right one!)

[ink-engine-runtime.dll.zip](https://github.com/inkle/ink/files/847377/ink-engine-runtime.dll.zip)

I believe that should work, so once you've verified, I'll upload a new version of the Unity package with the fix to the releases page.

**Comment by jjsonick** [comment]
That version of the dll works!  Thanks!
