### ISSUE TITLE
Stat tracking from GDC talk

### ISSUE THREAD

**Issue by nicholasderk** [inkle/ink#307]
I've been attempting to recreate the "tension" system from http://www.gdcvault.com/play/1021775/Adventures-in-Text-Innovating-in but I do not have a development background and I must be missing something.

I've created the following prototype project to try and figure out how the math works but it is always coming back as 0.

```
-> start

VAR tension_up = 1.00
VAR tension_down = 1.00

=== function high_tension
~ return (tension_up / (tension_up + tension_down)) > 0.7

=== function medium_tension
~ return (tension_up / (tension_up + tension_down)) > 0.4

=== function low_tension
~ return (tension_up / (tension_up + tension_down)) < 0.4

=== start

Tension Up is {tension_up}.
Tension Down is {tension_down}.

Tension value is {high_tension()}.

+ Add Tension
~ tension_up++
+ Lower Tension
~ tension_down++
- -> start
```

I know it's amateur hour but any help would be appreciated.

**Comment by nicholasderk** [comment]
Need a bump as I've still been trying to get this work.

**Comment by ZephyrRaine** [comment]
Interested too, good luck!

On Jun 10, 2017 05:51, "nicholasderk" <notifications@github.com> wrote:

Need a bump as I've still been trying to get this work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/inkle/ink/issues/307#issuecomment-307539785>, or mute
the thread

**Comment by joningold** [comment]
Hey!

So your code is fine except for a few things, I think.

First up, don't make infinite loops!! It tends to freeze Inky. Stick a
choice on that start loop

+ loop -> start

Secondly, the maths is fine, but remember "high_tension" is just a boolean
- it's 0 because it's returning "false". It's returning false because you
keep adding to both high and low, so the balance is stuck in the middle.

Here's a quick rewrite:

-> start

VAR tension_up = 1.00
VAR tension_down = 1.00

=== function tension_value
~ return (tension_up / (tension_up + tension_down))

=== function high_tension
~ return tension_value() > 0.7

=== function medium_tension
~ return tension_value() > 0.4 && tension_value() < 0.7

=== function low_tension
~ return tension_value() < 0.4

=== start

Tension Up is {tension_up}.
Tension Down is {tension_down}.
Tension value is {tension_value()}.

You're feeling {high_tension():tense|{medium_tension():normal|relaxed}}.

{shuffle:
-   Add Tension
    ~ tension_up++
-   Lower Tension
    ~ tension_down++
}

+ loop -> start

cheers
jon

**Comment by nicholasderk** [comment]
Yes! #Yes
