### ISSUE TITLE
Word wrap bug when writing ink files in sublime

### ISSUE THREAD

**Issue by jamiesirvo** [inkle/ink#35]
When I write an ink file, text wraps on the line instead of on the word.  This makes long blocks of text difficult to read/write.  
I've attached an example showing that the issue is ink-specific.  Is anyone else getting this behavior?  Is there a simple setting I've missed that would allow me to restore word wrapping?

Thanks!

<img width="757" alt="sublime_ink_wrap" src="https://cloud.githubusercontent.com/assets/18056344/14056935/477d6316-f2b0-11e5-8558-b6bd94ca8bf6.png">
<img width="754" alt="sublime_textfile_wrap" src="https://cloud.githubusercontent.com/assets/18056344/14056937/4de6ff1e-f2b0-11e5-9cad-638860734b83.png">

**Comment by joethephish** [comment]
Interesting. It seems that Sublime overrides the word wrap settings depending on the exact content, and that depends the semantic names used in the ink theme. Specifically, I had normal text content being classed as `string.content` before. After turning that off, it fixes the word wrapping. Hurrah! (Fixed in 4887f5a7011cb25d1b51860c025aae2ca54b55d1)

I also noticed in your screenshot the hanging indent, which seems a bit wrong. By changing the root scope from `source.ink` to `markup.ink`, it seems to change that setting, so that it's more like plain text or markdown. The hanging indent is probably undesirable. For choices it's actually quite nice, since it indents beyond the original `*` on subsequent lines. It's probably not worth it though - having hanging indents everywhere because Sublime thinks that it's more like source code than text is probably the wrong way around. (Fixed in 7222bb2f7a23947bf8419703730a0fe73c83f5cd)

So grab latest and run the install script to update!
