### ISSUE TITLE
Sequence with blanks vs condition

### ISSUE THREAD

**Issue by y-lohse** [inkle/ink#361]
Hi! The following ink:

```
{one||two}
```

produces this error

```
Expected right side of '||' expression but saw ||two
```

But it's supposed to be a [sequence with a blank element](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#features-of-lists). It probably doesn't matter, but it's not a real use case, I just found it while writing tests for inkjs.

That's in inky 0.7.2 (on mac), but IIRC those errors are pulled from inklecate so I'm reporting it here.

**Comment by joethephish** [comment]
Yeees there’s unfortunate syntactic ambiguity between a few little things like that. Usually there are ways around them though so I’m not too concerned?

**Comment by joningold** [comment]
As Joe says, that's the intended reading here. The reality is we should,
really, have a leading character to tell ink that a list is a stopping list
and not think about it as a conditional; otherwise how do we deal with

{knot:rope | squiggle:line}

...should "knot" be a knot name?

But - we've tossed around designs for this, but the current hacky default
is just so useful...!

Jon

**Comment by y-lohse** [comment]
No worries, it was indeed easy to work around it in my case. Feel free to close this issue if it's otherwise on your radar or whatever !
