### ISSUE TITLE
Feature request: Generating a dialogue tree and starting dialog from any place in script

### ISSUE THREAD

**Issue by TomoCZ** [inkle/ink#362]
It took me almost one year to find this great game screenplay writing software that suits my needs unlike others, even not free and totally profesional programs.

Anyway, in order to help in orienting in long and complex scripts it would be awesome to have a posibility to generate some sort of dialogue tree. Not for manipulating or something (that would be too much to ask), but just for beeing able to view it which would help author and more the others in team to better orient in the branches.

The second thought of mine is adding some kind of possibility to start "playing" from different points in the story, not just the begining. Of course there is the problem with variables and stuff, but maybe it could be solved in adding posibility to set the needed variables before starting playing.

Thank you for doing great job! :)

**Comment by facelesspanda** [comment]
Seems you have things mixed up.

`Ink` is a language, not a software.
`Inklecate` is a compiling software that takes one or more .ink scripts and creates one JSON story file
`The Ink Engine` is a C# library that takes that JSON story file and helps any C# software to fetch "the next line(s)" and interact with the story written with ink by the Author. There's also a JavaScript version I think, but not here in this repo.

What you ask (a visual tree) is beyond the scope of `Ink`, `Inklecate` or `The ink engine`, because none of these things are visual software themselves. You may be referring to [Inky](https://github.com/inkle/inky), which is an ink script editor. I invite you to address your request there if it is indeed what you had in mind.

As for "starting from anywhere" it's already possible. I don't know how it's done with Inky, but the Ink Engine's API has methods for moving the "story cursor" at any knot or stitch you want. See [Running your Ink](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md)

**Comment by TomoCZ** [comment]
Ah, you are right. I am sorry. Now I understand it a bit more, thank you for explanation.
