### ISSUE TITLE
Bug: function returning wrong value into a ? test

### ISSUE THREAD

**Issue by joningold** [inkle/ink#394]
The following...

```
LIST SomeList = ItemA, ItemB

{ SomeList ? returnItem(0) } 
     
=== function returnItem(x) 
    { x: 
        - 1:    
            ~ return ItemA 
    }
    ~ return ItemA   
```

produces a run-time error (can't test ? between List and Int), because somehow the function is being treated as returning an int, not a list item. But if you just call the function 

`{  returnItem(0) } `

...you do get the right result!

**Comment by joethephish** [comment]
This was another case of conditionals leaving a garbage value on the evaluation stack instead of cleaning up after themselves. When there was a switch-like statement and all branches fail, it left garbage (in this case an int), meaning it returned the wrong value. Fixed in eebcd6464d8444036d68dc0a3e6c37d29e9aca34.
