### ISSUE TITLE
Investigate TOML for file size savings

### ISSUE THREAD

**Issue by gamedevsam** [inkle/ink#4]
Tom's Minimalist Language is super simple,  requiring way less text than json, but still as powerful and flexible: https://github.com/toml-lang/toml/blob/master/README.md

**Comment by joethephish** [comment]
Thanks - looks like an interesting format.

The biggest problem we have with the file size right now isn't actually JSON's fault at all - it's our implementation that could be optimised. And, in general we'd prefer to use JSON for broad compatibility reasons, so that it would be native on a JS runtime (one day hopefully!)

If we do go with a non-JSON, more proprietary format, we'd prefer to roll our own, that's both optimised and reasonably human readable/debuggable for our needs.
