### ISSUE TITLE
Unexpected behavior for Knot parameter. 

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#40]
I encounter a problem which I believe is caused by the use of a reserved word, hidden variable, or token value as knot parameter.

Both knots in the following snippet are functionally identical. Despite this, one prints out the correct value of 0, and the other, an incorrect value of 1. The only difference appears to be the name of the parameter.

Would it be possible to have the compiler catch this, whatever the root cause is?

```
== Begin ==
Fun with params
+ Toggle Lamp (working) -> ToggleLamp(false)
+ Toggle Lamp (broken) -> ToggleLamp2(false)
* I'm Done -> DONE

== ToggleLamp(isOn) ==
the lamp is on? {isOn}
-> Begin

== ToggleLamp2(on)
the lamp is on? {on}
-> Begin
```

**Comment by joethephish** [comment]
Hmm, this appears to be possibly related to an issue that we're seeing here internally, that some parameter names (wrongly) conflicting. For reference, he's a small repro for the issue we're seeing:

    == knot ==
    - (x) -> DONE

    == function f(x) ==
    Nothing

Compiler gives error: `ERROR: Argument 'x' conflicts with a Gather on line 2 of test.ink,  on line 4 of test.ink`.

**Comment by joethephish** [comment]
Okay, those two things were entirely unrelated. Fixed both though.

You're right, I forgot I'd experimentally added `on`, `off`, `yes` and `no` as synonyms for `true` and `false`, which doesn't really bring anything, and significantly muddies the list of reserved words. Worse, it wasn't even giving you an error, but silently replacing your variable with a 1 or 0!

Fixed in development branch, will merge into master and do a new release build soon. In the meantime, just rename your variables please!
