### ISSUE TITLE
Variables Across Multiple Ink Files

### ISSUE THREAD

**Issue by glowygirl** [inkle/ink#403]
I'm making a game in Unity for a school project, and am using Ink for the dialogue. I'm trying to spread the dialogue over many different Ink files, because the character that speaks isn't always doing so -- a dialogue bubble will pop up when they start talking and disappear once they're done. It seems easier to me to write a script that will determine which Ink file to use rather than having one giant Ink file and somehow telling it which section to start at. I've used this method before, but what's different now is that I need the dialogue to reference choices made by the player in previous conversations. 

My problem is that I used a method that I thought would work, but it's not, of course:

I've set up a Variables.ink file, which so far just has one test dummy boolean, "personality_nice". I have two other files, one being the intro (which pops up immediately at the start of the game), and then the next conversation, which is triggered by a checkpoint I've set up. Both files reference Variables.ink, but when I play the game, the second conversation thinks that "personality_nice" is false when I supposedly set it to true in the intro. So, clearly, the change isn't being passed on to Variables.ink or isn't being saved after the first conversation ends. I just don't know how to fix that.

I combed through a ton of these issues and whatnot but couldn't find my exact problem... I did find something about having a Variables.ink file, so I hope I'm on the right track. 

Does Variables.ink need to reference all my other conversations that will change any variables (seems inefficient)? Do I need to do something with the saving/loading functionality? Should I abandon this method and use a single Ink file for the whole game? Thank you so much in advance for your help.

**Comment by facelesspanda** [comment]
You don't have to bundle all your scripts into one file, but you do need to load one single story in your game.

I don't know exactly what you're doing with your "multiple files", but here's how I would do things:
- keep the `variables.ink` file (it's a neat idea to keep the logic initialization in an easy-to-find place)
- have the conversation files because why not, it's still cool to be organize
- don't include `variables.ink` in each conversation because that duplicates the code
- create a `story.ink` file that `INCLUDE`s all the other files.

then you can compile the story into its own `.json` file and load that into the game.

Now, you also need to keep in mind that you **need** to tell ink where to go when you want to change story locations.

`Story.ChoosePathString` is a great tool, don't overlook it.

**Comment by Dougomite** [comment]
Excellent, this was the first hurdle I ran into while getting Ink working in Unity as well. Thanks for the tip.

**Comment by glowygirl** [comment]
@facelesspanda Thank you for your answer; I've figured it out. Including all the separate conversation files in the single `story.ink` file didn't work out, so I'll have to keep all the dialogue within that single file -- I'm worried about it getting too large to efficiently handle, but I guess I'll cross that bridge if/when I get there. 

For the time being, my system plays specific conversations when I want it to, and correctly keeps track of variables, which were the most important things for me!
