### ISSUE TITLE
Is there string processing operation(or function) in ink?

### ISSUE THREAD

**Issue by zhouzhongcheng** [inkle/ink#418]
Is there string processing operations(or function) in ink? ie. substring(),  split   .etc.

**Comment by facelesspanda** [comment]
No there's not.
The only string operations Ink supports are the concatenation, and examinations (equality and contains).
https://github.com/inkle/ink/blob/32fa48a251826d82b9e4e36b04f147bf577a05e5/ink-engine-runtime/NativeFunctionCall.cs#L354-L357 
This sort of heavy computation is better left to the game engine through external functions.

**Comment by zhouzhongcheng** [comment]
Ok,Thanks.

**Comment by teichert** [comment]
Would someone be willing to explain the justification here a bit more? (That is, should we understand this to be a deliberate and final design choice, or just a potential feature with low priority?)

I can understand including a note or warning that some builtin functions might not be as efficient as external functions in the game engine, but I don't quite see why LENGTH(str) and SUBSTRING(str, start, length) would be in a different league from string "Add" and "Has" (except that they aren't binary operators).

Even if functions requiring Length and Substring are better left to the game engine through external functions, IMHO, having a viable (even if suboptimal) fallback that is possible within Ink would be a huge step. (Technically, it is theoretically possible to implement LENGTH and SUBSTRING within Ink: e.g. for LENGTH, once could recursively iterates over all possible strings from length 0 onward until the input string is matched at which point the length is known; however, that solution is clearly not actually viable.)

I suppose my main question is whether the maintainers would consider accepting a pull request that adds SUBSTRING and/or LENGTH to Ink.  Thanks!

**Comment by joningold** [comment]
So it’s mostly because we never needed them - but they are pretty easy to
implement as external functions so it’s low priority too. Otherwise there’s
some small value in keeping the runtime code smaller.

(We added the ? operator to strings because we needed it but could have
done it via an external.)
-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by teichert** [comment]
Thanks @joningold for the quick reply!  That makes sense.  So it sounds like you'd be more willing to consider a pull request if the implementation is very small.

Thinking of how to make the implementation as small as possible, an alternative to native `LENGTH` and `SUBSTRING` that would still allow them to be implement in Ink code would be to provide two native functions (`STR_HEAD`, and `STR_TAIL`) that could be implemented in the C# code-base as unary string operators requiring just a couple lines of code each in [NativeFunctionCall.cs](https://github.com/inkle/ink/blob/67eabb4ba1fdafda4cc53faad8453d41400be79f/ink-engine-runtime/NativeFunctionCall.cs).  `STR_HEAD` would return a string containing the first character of the operand (or an empty string if the operand is empty) and `STR_TAIL` would return the remainder of the operand after skipping the first character if present.

These functions would be added as unary string operators just like `MAX` and `MIN` are binary int and float operators, so that will be very little code to change in the runtime.

The main benefit is that they would make it possible to at least write working fallback functions in Ink for `Length` and `Substring` functions which in-turn provide a way to have an ink container that includes repeats (I don't see any way to do this in ink currently without exponential runtime complexity, but I'd be happy to hear that I've missed something!).  (`STR_TAIL` alone would allow a recursive implementation of `Length`; adding `STR_HEAD` would allow a recursive implementation of string indexing and the more general `Substring` all within Ink.)

**Comment by joethephish** [comment]
Sorry, I realise that it's relatively straightforward with a small amount of code, but I'd rather not accept a pull request for this right now. As Jon says, it's relatively easy (and almost as performant) to implement it yourself. Given the relative lack of demand for it, I'd rather this was left to the developer to add their own external functions.

**Comment by teichert** [comment]
I can understand that (and thanks for the response and great project!).  To clarify, it is easy to implement those functions in a game engine but impossible (AFAIK) to implement them in Ink.  That means that anything that relies on the functionality cannot be used within, e.g., Inky and [quill](http://jeejah.xyz/quill/).

For context on my use case:  I was recently introduced to Ink and have been using it to expose non-programmers and beginning programmers to programming concepts (it has given them a connection between programming and story telling and other fields).

It has been surprisingly easy to show much of what I want to show, but the lack of `STR_HEAD` and `STR_TAIL` represents a significant limitation on what code students are able to just paste and run in Inky or quill.  Unfortunately, the extra steps needed to use external functions is just too big of a barrier for their use-case.

**Comment by joethephish** [comment]
I see what you mean, yeah. Sorry about that...!

**Comment by limitcracker** [comment]
Hi, how I could add a String to a list? The following code

```
VAR yliko = "Τυρί"
LIST ylika = Burger, Ψωμάκια
~ ylika += ~{yliko}
{ylika}
```
 does not work it gives error:
`Can not call use '+' operation on List and String`
