### ISSUE TITLE
Question: Any plan for upcoming release?

### ISSUE THREAD

**Issue by fireton** [inkle/ink#423]
Latest release was almost a year ago. Any plans to release new exciting features like non-ASCII character sets for knot names? I know you working on a game but...

**Comment by joningold** [comment]
Prosaic answer I’m afraid - we’re working on a game so the only features going in are ones we need! Feel free to develop and send a PR if you see something you need, however.

**Comment by joethephish** [comment]
Yup, non-ascii sets for identifiers (knot names, variable names, etc) are working in the ink repo since August but I haven't put out a release since June last year I'm afraid! (For reasons already mentioned!)

![characters-sets](https://user-images.githubusercontent.com/858967/38795393-fea6123c-414f-11e8-9f76-da966b495c90.jpg)

Though even I'm a bit shocked by how long it's been since our last release so maybe I should set aside some time to do one!

**Comment by fireton** [comment]
@joethephish, I know that non-ascii is in the repo for a pretty long time. But not in Unity helper release, I'm trying to make some ink game with Unity and non-ascii would be really cool for me.

I understand that the new game is in the top priority for you. But it would be great to see a new release in some time soon.

**Comment by joningold** [comment]
Your wish is not our command, but nonetheless, it has come true!
