### ISSUE TITLE
[Bug?] Premature evaluation of external game state

### ISSUE THREAD

**Issue by dylsg** [inkle/ink#424]
I've created a simple repro of the problem using the example project.

Here's the story.ink:
```
EXTERNAL IsCharacterDead()

Hello
KILL_CHARACTER // mark up to the game to kill the character
{ IsCharacterDead(): // external function
	Character is dead.
}
-> END

```
The output is:
```
Hello
KILL_CHARACTER
```

Which seems strange because I was expecting "Character is dead." to be printed as well.

If I modify story.ink by adding an else case:
```
EXTERNAL IsCharacterDead()

Hello
KILL_CHARACTER // mark up to the game to kill the character
{ IsCharacterDead(): // external function
	Character is dead.
  - else:
        Character is alive?
}
-> END

```
The new output is:
```
Hello
KILL_CHARACTER
Character is dead.
```

I've read [the post](https://github.com/inkle/ink/issues/253#issuecomment-272395950) about look ahead. Here, it seems like in the look ahead, when there is no text encountered, the ink runtime does not restore to the checkpoint? (Which it should in this case because the external game state has changed, and IsCharacterDead **should** be re-evaluated.)

[InkSample.zip](https://github.com/inkle/ink/files/1931316/InkSample.zip)

**Comment by joningold** [comment]
That looks a lot like it's looking-ahead while running Continue on the KILL
CHARACTER, skipping over the if condition because it's currently still
false, hitting END and that's causing the flow be immediately killed.

We've seen this issue in a similar context, our work-around was to add a
literal >>> DO NOTHING instruction, which is ignored by the game-side.

I think a proper solution would be to introduce a genuine "action
statement"  type, which the game knows that, once found, will do things
that might change game-state.

**Comment by dylsg** [comment]
Thanks for the quick reply! 

It's true that the DO NOTHING instruction could solve the issue, but my worry is that there are many more of such cases lurking around in our game. It's near impossible to cover all the possible runtime game states.

We almost never use the glue feature anyway, and we've been burned a few times by subtle look-ahead issues like this one. So we are actually considering disabling the look-ahead.

I've taken a peek at the ContinueInternal() function inside Story.cs, but I'd really appreciate any pointers regarding the feasibility of disabling look-ahead.

**Comment by joningold** [comment]
It should be feasible. There's a bit of code commented as

"We're going to continue stepping in case we see glue or some non-text
content such as choices."

And if you don't do that, but just break out at that point, I think it
should work. Note forward glue will still work, I think.

A <>
B

One other thought I had was, try using -> DONE instead of -> END in your
test case. It may make no difference, but there's a chance it will.

cheers
jon

**Comment by dylsg** [comment]
Thanks jon! I'll give it a shot.
