### ISSUE TITLE
Can't compile, unhandled exception.

### ISSUE THREAD

**Issue by tomkail** [inkle/ink#432]
The report comes from this on the unity integration package: 
https://github.com/inkle/ink-unity-integration/issues/61
Here's the user's log (from inky, I think?)
<img width="858" alt="screen shot 2018-05-07 at 07 50" src="https://user-images.githubusercontent.com/1252816/39689919-443a8b94-51d0-11e8-820c-1a4d9e0918a6.png">
<img width="868" alt="screen shot 2018-05-07 at 07 50 1" src="https://user-images.githubusercontent.com/1252816/39689916-44112d08-51d0-11e8-9ca7-3c2dcf1c93f2.png">
<img width="869" alt="screen shot 2018-05-07 at 07 50 2" src="https://user-images.githubusercontent.com/1252816/39689917-4426f4b2-51d0-11e8-8563-da3f125649b4.png">

**Comment by joethephish** [comment]
Hey @Laurenannmarie88, can you post some ink that causes this issue, ideally reduced down as small as possible? Or, if you'd prefer, feel free to send me the ink privately (joe at inkle studios dot com).

**Comment by joethephish** [comment]
Here is the minimal repro I could build from the ink file supplied:

```
==Knot
~ f(Knot)

=== function f(ref x)
~ return
```

**Comment by joethephish** [comment]
There were actually 2 bugs found in the original source:

* We needed to give proper errors when attempting to pass a read count as a variable reference, instead of crashing. Fixed in 334a720e55232a4944d21381cbf4a7302db1e9b2.
* We weren't checking for naming collisions between stitches and higher-naming-priority entities such as VARs. Fixed in ce97a35fe7caa54601af5f344422dc281919cb3a.

The latter was the primary error in the original source, since there was a VAR with the same name as a stitch, causing an *accidental* read count to be passed by reference.
