### ISSUE TITLE
Zero-valued list entries are "false" which is odd

### ISSUE THREAD

**Issue by joningold** [inkle/ink#437]
The following:
```
LIST values = nought = 0, one = 1 
{ nought: zero | non zero }

```
produces the output "non zero". More to the point, if you're looping through a list and grabbing the LIST_MIN of it on each pass, you can't tell the difference between () and "has a value of 0".

The "truthiness" of a list item should probably just be "is it not ()", not "is it not () and not 0".

**Comment by joethephish** [comment]
Right yeah, just looked at the code, and it does seem like my head was very much in the space of the feature resembling C-style enums more than anything (at the time), with the philosophy being that they predominantly represented int values, therefore they should have the same behaviour as an integer.

But yeah, I agree, we do use lists more like collections / sets, so the non-empty test does seem more sensible. Fixed in 6c8973efad8e5c2980b8b17beff805aad46b561c.
