### ISSUE TITLE
Double spaces not being cleaned

### ISSUE THREAD

**Issue by y-lohse** [inkle/ink#447]
I caught a tiny regression [while porting the latest ink changes](https://github.com/y-lohse/inkjs/pull/139#issuecomment-404155647):

```
~ temp met_blofeld = true
I… {met_blofeld: I saw him. Only for a moment.}
```

This will now produce `I…  I saw him. Only for a moment.` — with two spaces after the `I…`. You can't see it here on github because html collapses double spaces, and for the same reason it has no ill effect on inky or inkjs. No idea about Unity, but anyway.

It looks like the problem is that `CleanOutputWhiteSpace` [copies all the output from the first whitespace it encounters](https://github.com/inkle/ink/blob/master/ink-engine-runtime/StoryState.cs#L191), so they both get copied.

**Comment by joethephish** [comment]
Hmph, now I wish I had written better comments! I'm unsure about what that `CleanOutputWhitespace` method is attempting to achieve exactly.

It *looks* like it's attempting to simply strip *trailing* inline whitespace before a newline. e.g, replacing spaces with dots for clarity: turning `hello..world...\n` into `hello..world\n`. If it was simply attempting to collapse all inline whitespace to single spaces (HTML style) then it wouldn't be mentioning the `\n` at all, and it would be simply appending a space rather than appending a substring.

Of course, whether this was a sensible intent is another question entirely :) Since it only took some very minor tweaks to turn this into a more useful method that does such cleaning, I have now done that in f59bd3321c74e9360b9545ba9496e38073b10926.

(The fact that the previous version did this before was kinda luck, but it does make sense to keep it explicitly!)
