### ISSUE TITLE
How do you alter a variable from its initial value?

### ISSUE THREAD

**Issue by SerpentineRain** [inkle/ink#459]
If I wanted to allow a player to choose a race based off of a dialogue choice and save it to a variable, such as:

-(Race)Race:
+-Terran-
Description. 
    Are you a Terran?
    **[Yes]
    VAR PlayerRace = "Terran"
    The word "{PlayerRace}" appears next to race.
    **[No]->Race
+-Novian-
Description.
    Are you a Novian?
    **[Yes]
    VAR PlayerRace = "Novian"
    The word "{PlayerRace}" appears next to race.
    **[No]->Race

I can't re-declare PlayerRace in a separate choice. I'll just get an error that the choice was already declared, because it was. 

My question is how do you re-assign or change the value of a variable in ink without re-declaring it? It's especially confusing considering that the variable is only supposed to be assigned if the player chooses that option. Is there a better way to go about it? 

Any help would be appreciated :)

**Comment by SerpentineRain** [comment]
Super late night question. May have just needed to sleep on it, but eh. Also, is there a better way to embed code into an issue? 😮
Sorry in advance if it's messy. Super new at all of this!

**Comment by joningold** [comment]
So, a line like

VAR PlayerRace = "something"

initialises the variable: it tells the game the variable exists, and what
to set it to *at the start of the game*.  You can put that line anywhere
you like, and it won't make any difference; but you can only have it once.

To actually *set* the variable, use a ~ line

~ PlayerRace = "Terran"

... and these happen "in the flow"; so that's what you should be using
here.

Good luck!
jon

**Comment by SerpentineRain** [comment]
Oh thank you so much! I know they said how to initialize the variable in the documentation, but I kept re-reading and couldn't find anything on how to set the variable? Maybe I just overlooked it though haha
I actually just started learning last night, so it was probably a really beginner sort of question. All my errors are gone because of one little tilde! You're the best :)
