### ISSUE TITLE
Is there a way to italicize text, for example narration?

### ISSUE THREAD

**Issue by WinterHasLeft** [inkle/ink#520]
Not sure if this'll get seen anytime soon but if it does, wonderful. But I just started a project and I've already hit an issue I can't seem to pass. The story I am writing is a multiple choice adventure, and every choice you pick, a narrator states. Like: Option A: Walk Through the door. _"You walked through the door."_ and the second part would be obviously italicized. But I cant figure out how to do so. Did I miss something in the help section or is there no way to do this? Thank you

**Comment by lcizzle** [comment]
Hello!

I'm not sure your issue is an issue of Ink. Ink wasn't really made to stylize the text output. That is a job for you to handle in your game code. Simply tag the text you want to appear a specific way and then extract the tab in your game code and handle the change in style before printing to the display.

Ink Web Export
https://github.com/inkle/ink/issues/396

Example code found in The Intercept.
https://github.com/inkle/the-intercept/blob/master/Assets/Scripts/Utils/RichTextSubstring.cs
