### ISSUE TITLE
"Structured JSON-like data objects within ink format"

### ISSUE THREAD

**Issue by ahayworth** [inkle/ink#546]
Hi all! This morning, I noticed this little bit on the "probably coming" [section](https://github.com/inkle/ink/blob/6d75726c2c9a21af9734337749778df58ed76dca/README.md#probably-coming) of the README:

> Structured JSON-like data objects within ink format. Exact design still to be determined, but goals are for it to be a superset of JSON, so that it’s compatible, but can be simpler (a bit like YAML, though not YAML for various reasons). Would allow more complex hierarchical game state to be stored within the ink engine.

I was wondering - is that still "probably coming"? I'm working on a project using Ink, and knowing if that is coming someday will influence the design of my own game-state layers.

Thanks so much - and thank you for making such a cool IF system available!

**Comment by joethephish** [comment]
Sorry I'm afraid that's probably not coming after all! Back when we wrote that we thought we'd probably build that at some point.

Right now I'm feeling less like it's a good idea, since it would add more complexity to the engine than feels strictly necessary, and would also encourage overuse of ink as a full blown programming language. If you go too far down that path you'd end up disappointed since it would probably end up feeling very slow if you did too much in it!

In general we recommend doing complex logic on the game side, and keeping your specific narrative-relevant state in ink, such that it can be modelled with the constructs we do provide.

I'll take a moment to update the README!

**Comment by ahayworth** [comment]
Sounds good, thank you for the update!
