### ISSUE TITLE
Bug: glue-lookahead-rollback doesn't roll back pure logic

### ISSUE THREAD

**Issue by rabidgremlin** [inkle/ink#556]
Just looking for clarification on when the Continue() method stop processing.

If I have the following code:

```
VAR a_test_value = 100
This is a test
:RUN_TEST_FUNC
~ a_test_value = 50
```

And ```:RUN_TEST_FUNC``` is recognized by my game engine as an instruction to do something (as documented in https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md with the ```>>> SHOT:``` example) 

And my ```:RUN_TEST_FUNC```  retrieves the value of ```a_test_value``` (```story.variablesState["a_test_value"]```)

Then using ```story.Continue()``` the value of ```a_test_value``` is 50 when ```:RUN_TEST_FUNC``` is returned not 100.

I assume that is because Ink including the ```~ a_test_value = 50``` in its processing. **Is that correct ?**

**Comment by rabidgremlin** [comment]
Also thsi behaviour seems inconsistent. With the following code:

```
VAR a_test_value = 100
This is a test
:RUN_TEST_FUNC
~ a_test_value = 50
A test is now {a_test_value}
```
```a_test_value``` is 100 when ```:RUN_TEST_FUNC``` but is 50 when the ```A test is now {a_test_value}``` line is processed.

**Comment by joningold** [comment]
As the poster above says, that looks like a bug to me - ink runs forwards, looks for glue, then rolls back; but a line which is "pure logic" it might not be bothering to roll that back. It's definitely unhelpful behaviour though.

(I'm surprised this is happening as we use this kind of instruction all the time; makes me wonder what weird bugs we have in our games.....!)

**Comment by joethephish** [comment]
I'm not managing to reproduce this. Can I see your test code for it?

**Comment by joethephish** [comment]
Hmmm, so this is much more subtle than I expected. It only happens at the very end of evaluation. So, for example:

```
VAR x = 0

// First Continue call(s) evaluate the following:
~ x = 1
A

// Last Continue call evaluates the following:
~ x = 2
B
~ x = 3
```

So, any final logic will get grouped into the final Continue call.

We spent a while considering this, because it seems quite surprising! But we actually think it's the right approach. The high level goal is that the number of Continue calls matches the number of lines of text produced. You can see this in action with the way that a final Continue call before choices produces the choices at the same time.

We don't like the idea that you have to do one more final Continue call to get pure "final logic" effects since it can get even more subtle. For example:

```
A
-> the_end

=== the_end ===
-> END
```

Do you have to do another Continue call after seeing A, in order to get the story to fully finish? We don't think so. There are more logical state changes that happen at this stage - the read count of the_end increases by one, so really it's no different than an explicit `x = 5`.

The primary goal of ink is to be a text engine with a simple runtime API that allows you to say "now give me another line of text", and I think if we were to orient it more around logic and side-effects, it would take us down an even more confusing rabbit hole!

**Comment by rabidgremlin** [comment]
@joethephish Thanks for looking into this. I understand what you are saying. 

Unfortunately our use case is a bit trickier then the examples above. Basically between calls to Continue() our engine may set the value of Ink variables for further evaluation during the next call to Continue(). Often this evaluation results in the conditional generation of content (or no generation of content).

So if Ink doesn't "roll back" to the last line of text output, then in our case, content gets incorrectly generated (or not generated) because the "pure logic" has already executed :(

I'm guessing that to take your points above into account and our issue that perhaps when the Ink engine is processing a Continue() it needs to stop at the first "conditional" it encounters ? This will allow the state of the ink engine to be changed externally between Continue() calls with the correct conditional logic getting applied.

**Comment by joethephish** [comment]
So, this is slightly subtle, but it's not actually related to the lookahead glue stuff or rolling back. Even if we took that out of the engine, we'd have the same behaviour - it's more to do with the behaviour that we want on the last line of content before `canContinue` returns `false`, whether that's at an ending or a choice point.

And I do understand the use-case. We do this ourselves in our games too - generating content one line at a time and potentially manipulating state in between.

I feel like there's something I'm maybe missing in the specific way your ink is authored or another way to reproduce this issue that I haven't considered. Because as I mentioned, it should only be an issue at the end of a piece of content on the last `Continue()` call based on my tests. So in a slightly more fleshed out example, is this at a choice point or at the end of a story or somewhere else? If it's a genuine end point, could you do something hacky like add `:END_STORY` that forces your final piece of logic to be delayed until that text is seen?

For example, since you mentioned conditionals, I can see this would be problematic:

```
VAR x = 0

Hello
{x > 0:
    world
}
```

Since you can't write:

```
story.Continue();
story.variablesState["x"] = 1;
story.Continue();
```

...since it would already have finished on the first line. But if you change the story to:

```
VAR x = 0

Hello
{x > 0:
    world
}

:END_STORY
```

...then it would work ok?

**Comment by rabidgremlin** [comment]
I think there a number of quirks to they way we are doing things that are all contributing to the issue. I'll try and create a succinct example to reproduce the issue.

**Comment by rabidgremlin** [comment]
Haven't been able to create a more reproducible case. However we have managed to "fix" most of our issues by using the latest version of blade-ink 0.7.3 (the Java port of ink we are using). Happy for you to close off this issue if you want.
