### ISSUE TITLE
RANDOM doesn't work when difference between inputs is very large

### ISSUE THREAD

**Issue by Fendse** [inkle/ink#559]
Attempting to call `RANDOM` with two input values such that the minimum is smaller than the maximum by at least 2147483647 (such as if calling `RANDOM(0, 2147483647)` or `RANDOM(-1200000000, 1200000000)` produces a runtime error with the message `RANDOM was called with minimum as [minimum] and maximum as [maximum]. The maximum must be larger`.

**Comment by joethephish** [comment]
This will be because the underlying integer parser fails to parse a number larger than it can store. Internally the codebase uses `int.TryParse()`, so it will be failing and using zero. Hence, it'll be doing `RANDOM(0, 0)` internally.

We cooooould move from 32 bit to 64 bit integers but I don't think anyone has explicitly called for it? And I suspect it would open a few more cans of worms!

What we should do is give a proper error if you try to use a number that exceeds the bounds of a 32 bit integer.

**Comment by joethephish** [comment]
Oops, reading your original post more closely - yes I see the integer overflow issue too. Both now fixed in d010c3a368cf03539d3fdae67859341586ac64ba and d1f50713f64ba3b76b24c7816c70137d0eaf3d98.

The codebase could probably do with an audit for this kind of integer overflow stuff, I haven't done anything special to handle it anywhere until now.
