### ISSUE TITLE
Just write "06:00"

### ISSUE THREAD

**Issue by joaobsneto** [inkle/ink#561]
I want a line that's just "06:00", and a weird behavior emerged. An option in the middle of the text appeared that leaded to nowhere.
I found out that ink use the same text stream from content to send messages to the player itself. So if I write: "WARNING: 'file.ink' line 100: Some message", then a warning will apear in the editor.
That's not a problem for me, but I wanted to write a simple paragraph with the text 06:00, but I got, an option with label 00. And then I found out this is how options are exposed to the player {choiceIndex}:{label}. 
Is there a simple way to avoid that?
Thanks!

**Comment by joningold** [comment]
You can escape character using backslash, so 06\:00 will do what you want.

**Comment by joethephish** [comment]
Ah, I'm afraid the character escaping @joningold mentioned won't work here. It's purely an issue with Inky's player itself - you'll find that it doesn't happen anywhere else (including on web export or in Unity).

If you're making a game for a webpage you could put `&nbsp;` at the start, so: `&nbsp;6:00`. In Unity I guess you'd just have to strip that off by hand in C# code.

Either that or simply ignore it in Inky, since it's actually harmless, even though it's not appearing correctly!

**Comment by joaobsneto** [comment]
I'm making in Unity, but the writer is using inkle. Actually, I added a letter before it that I remove in Unity. So I'll keep with the solution. Thanks!
