### ISSUE TITLE
Resetting a knot with saving the choices made

### ISSUE THREAD

**Issue by Ragnar-II** [inkle/ink#583]
Hello!

So I'm using Ink with my game on Unity. The idea is an open world, where you can talk with a lot of NPC and do their quests. Each character has his own Ink file with his dialogues, and the knots represent scenes. If the player didn't make it to the next scene yet, dialogue is endlessly repeated. So in the end of each knot I have a label "return to the beginning".

What I want to do is the possibility to reset a dialogue if it's been interrupted. I can end the dialogue forcibly, but it means that Ink didn't read the return label. So next time I interact with NPC, it goes from the point where it stopped. 

My first thought was to make a variable tracking which knot we are in, and divert to it once interrupted. However, this means that choices are reset too. I can possibly save the choices made somehow, but how can I pass it back in Unity? And preferably without hardcoding it.

Is it possible to make some choices 1st time, and next time it's just the seamless text based on choices I made 1st time?

Thanks!

**Comment by Spois** [comment]
I stumbled across a similar issue some time ago and found a solution. It's not coded in ink though, but quite easy to do in unity. 

I implemented a class KnotLog.
So for every conversation knot the player visits, there will be a knotLog generated. 
During conversation the knotLog logs how many lines into the conversation the player gets and what choices he takes. To make this easier, you can just neglect the lines into the conversation and just remember the choices taken in the correct order. 

Just keep your knotlogs in a dictionary, check if you already have a KnotLog for a knot you are entering, and if so, iterate over it before the story continues, so it continues from where you left of.

You could probably implement something similar in ink directly but I found handling it from the outside way more convenient. Although that might be due to my lack of deeper knowledge, so I'll happily be corrected. :)

**Comment by Ragnar-II** [comment]
https://github.com/inkle/ink/issues/583#issuecomment-619403389

Thank you for your answer!

I actually managed to solve this on my own. All I did is to do a foreach loop on currentChoices[], and check if state.VisitCountAtPathString(choice.pathStringOnChoice) > 0. If it is, I simply choose this choice again, and we go on without prompting the player with the choice.

As a side feature, I made some of the choices "sticky" - if you actually need them to behave normally. To do that, I just put a 'sticky' tag before the choice in Ink.
