### ISSUE TITLE
Ink JSON Runtime Format documentation is out of date

### ISSUE THREAD

**Issue by foxfriends** [inkle/ink#586]
I am looking to understand how the Ink JSON runtime format works so I could attempt to build a runtime in Rust, but the documentation appears to be out of date. It mentions version 10, but Inklecate is outputting version 19. It also appears to have no mention of some features (lists, tags, or glue for a few) at all...

Would it be possible to update the documentation?
Thanks.

**Comment by joethephish** [comment]
Unfortunately parts of the runtime have pretty complex behaviour so I wouldn’t really recommend building it purely based on the JSON instructions, since you’d be missing 90% of the true problem. There would be a lot more I’d have to explain than the meaning of the symbols!

The JS port took the approach of trying to do a line-by-line conversion which guarantees compatibility as close as possible.

I understand that this wouldn’t really be possible with Rust though...! Sorry :-/

**Comment by foxfriends** [comment]
Yeah I see there's a lot more than in the docs. I was considering making even just a simpler one to match just what I needed, but still it seems complex. I will look for some alternative. Thanks

**Comment by joethephish** [comment]
Having a C (or compatible) library would be amazing since it could then inter-operate with lots of languages including Rust, but alas no one has made that yet! It’s probably an even harder problem than the JS port.

**Comment by LikeLakers2** [comment]
@joethephish Apologies for posting on such an old issue, but...

> so I wouldn’t really recommend building it purely based on the JSON instructions, since you’d be missing 90% of the true problem

I think pretty abundantly clear that the JSON format documentation isn't meant to be a "How-to develop your own Ink Runtime".

However, I would suggest *at the least* documenting the existence of things such as the glue commands (`"<>"`, `"G<"`, `"G>"`), so that I know they are something that *can* be output by the compiler. Even without instructions on how to handle them, this would then make it easier for someone to do their own research into how to handle those values -- meaning they may learn of the "true problem" you mention.

**Comment by ElnuDev** [comment]
Sorry to necro this issue, but I figured I'd comment in case anyone stumbles across this thread.

For using Ink in Rust, there is [bladeink](https://github.com/bladecoder/blade-ink-rs/) and it seems pretty robust. I used it a bit last year and it worked pretty well. It's been around for a couple years now and is still regularly updated it looks like.

> Having a C (or compatible) library would be amazing since it could then inter-operate with lots of languages including Rust, but alas no one has made that yet! It’s probably an even harder problem than the JS port.

@joethephish There are also [official C bindings for bladeink](https://github.com/bladecoder/blade-ink-ffi) but it doesn't seem like anyone has used them yet. I'm currently working on a project in Zig and will report back here what my experience with it is like once I get it working.
