### ISSUE TITLE
How do I remove an option from a loop?

### ISSUE THREAD

**Issue by Erilis000** [inkle/ink#589]
If this is the wrong place to post this please help me know where I should ask instead!

I've looked through the inklewriter tutorials and I still can't seem to figure out how to remove options from a loop once chosen.

One example would be asking a character questions and the questions (options) remove as you choose them until you select the one that takes you out of the loop.

I think they did this in Sorcery! with guessing what some writing says:
Lorag
Sansas
Greg

You'd see the options disappear as you choose them until you get the right name.

**Comment by architeuthis-facts** [comment]
Use * for choices that can only be made once, + for choices that are sticky. It sounds like you're using all +s.

**Comment by Erilis000** [comment]
Thanks so much for your response!

I'm using the asterisk and it seems to be working! 

The funny thing is, I'm not sure why! I haven't seen an asterisk being used anywhere in the tutorials and I'm not too familiar with coding.

I understand + and = but what is *? What does it mean?

**Comment by Erilis000** [comment]
I figured out how to do it with very simple Markers.
The key was to create a blank paragraph whose purpose is to show the options and put that underneath each option response.
[https://i.imgur.com/GVSWsDH.jpg](See my test here)

I'm still interested in learning more about what * does though, I'll try to do some research.
Thanks again for your help!

**Comment by architeuthis-facts** [comment]
It sounds like you've exclusively looked at the inklewriter tutorials? You might benefit from reading Writing With Ink, which is aimed more at people using Inky, Atom, etc:

[](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md)

* doesn't intrinsically mean anything, any more than the colon I used in the previous sentence means something by itself. It's a markup convention that changes the behavior of your compiled game. Writing With Ink actually treats * as the default choice bullet and + as a special case for loops, partly because there is an assumption that revisiting a choice will occur relatively rarely (not necessarily true, or a prerequisite for good ink). You can Ctrl+F that page for + to see a bunch of interesting situational uses for sticky vs. non-sticky choices.

**Comment by joethephish** [comment]
Hi @Erilis000 sorry but there’s some confusion between inklewriter (which you’re using) vs ink, which is the more “professional grade” game narrative scripting language which is mentioned (which uses * and + for different types of choices). This github issues page is for ink. So everyone commenting here is talking about different things!
