### ISSUE TITLE
Getting Over 90 errors when recompiling ink

### ISSUE THREAD

**Issue by manateabags** [inkle/ink#597]
Whenever I recompile Ink, it would give me a ton of compiler errors, saying that the compiler timed out.  I rebuilt the Ink library, I've tried recompiling multiple times, and many of the files that the compiler gave the error for don't have any special characters.  Any help would be appreciated!
![ink_CompilerTimedOut_1](https://user-images.githubusercontent.com/51467923/82865761-885a0b00-9ef5-11ea-8639-b591dc4d87d4.png)
![ink_CompilerTimedOut_2](https://user-images.githubusercontent.com/51467923/82865763-88f2a180-9ef5-11ea-9c7a-3df87a2a64de.png)

**Comment by tomkail** [comment]
Hey! That error message appears to be an old one, so the first thing to do is use the latest Unity package from https://github.com/inkle/ink-unity-integration.
I'd guess the error itself is because your story is just taking too long to compile - we have a compile timeout to avoid infinite loops, and you might be running up against it? On the "InkSettings" file in your project, try increasing compileTimeout.

**Comment by manateabags** [comment]
> Hey! That error message appears to be an old one, so the first thing to do is use the latest Unity package from https://github.com/inkle/ink-unity-integration.
> I see you have asserts in the log - can you show me what they're warning about?
> It's unlikely but possible that your story is just taking too long to compile - we have a compile timeout to avoid infinite loops, and you might be running up against it? On the "InkSettings" file in your project, try increasing compileTimeout.
> Failing that, if you send it over to tom.kail at inklestudios.com I'll take a look.

Yeah, I was able to fix it by updating the plugin.  Thanks so much for the help!
