### ISSUE TITLE
[HELP] How to bind dummy external functions for the editor player window?

### ISSUE THREAD

**Issue by crustforever** [inkle/ink#63]
Hi.  Forgive me if this is the wrong place to ask this question.

I'm getting a story exception when testing an Ink script in the player window because I have external functions defined.  Is there a good way to assign them dummy bindings in the editor only?  I see there is an allowExternalFunctionFallbacks flag but what does that do exactly?

I don't know how to get the Story object from the InkPlayerWindow script.  Perhaps an event could be added that fires when the window loads a story?

**Comment by joethephish** [comment]
Yeah, the player window sets allowExternalFunctionFallbacks to true, and this allows you to use an ink function as a fallback/placeholder instead of your actual external function in game code.

Just add a function to your ink file which has the same name and parameters as the EXTERNAL definition.

(If this doesn't work it may be because the allowExternalFunctionFallbacks option being set didn't make it into the latest integration release build but I believe it did.)

**Comment by crustforever** [comment]
Ah that's way easier than I expected.  Thanks!

**Comment by crustforever** [comment]
So I assume then when the story is used at runtime Ink prioritizes the EXTERNAL overload?

**Comment by joethephish** [comment]
Yup!
