### ISSUE TITLE
inklecate with json input

### ISSUE THREAD

**Issue by chromy** [inkle/ink#641]
In the (distant) past it used to be possible to pass inklecate some json and have it interpret that json directly, now that throws an exception:

```
~/s/ink (master|✔) $ /Users/chromy/src/ink/ReleaseBinary/inklecate/osx64/inklecate story.json
Unhandled exception. System.Exception: Object reference not set to an instance of an object. (Internal story path: <END>)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ink.CommandLinePlayer.EvaluateStory()
   at Ink.CommandLinePlayer.Begin()
   at Ink.CommandLineTool..ctor(String[] args)
   --- End of inner exception stack trace ---
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)
fish: Job 2, '/Users/chromy/src/ink/ReleaseBi…' terminated by signal SIGABRT (Abort)
```

Looking at the source [still some code for this mode](https://github.com/inkle/ink/blob/master/inklecate/CommandLineTool.cs#L88). The exception seems to be thrown because in json mode we [don't set compiler](https://github.com/inkle/ink/blob/master/inklecate/CommandLineTool.cs#L96) and we later rely on compiler [for some IO support](https://github.com/inkle/ink/blame/master/inklecate/CommandLinePlayer.cs#L100).

This mode is pretty useful in https://github.com/chromy/ink-proof because it makes it possible to test the inklecate compiler separately from the inklecate player/interpreter (which in turn makes it easier to compare to other implementations which only implement the 'player' logic). So far I've been hacking around this (see https://github.com/inkle/ink/compare/master...chromy:hack-to-support-json-input) but I would like a more long term solution.

I'm happy to work on this and send a pull request but before I started I wanted to know if you were still interested in having this mode as part of inklecate? And if so, any pointers on how you would like it solved? I could try to reuse parts of ReadCommandLineInput or it might be better to have a completely separate path for reading input in the json mode.

Thanks!

**Comment by joethephish** [comment]
Hey! Ah interesting, I hadn't considered this as an important use case and had actually forgotten about it entirely. Looking into it, it seems I backed myself into a corner with this dependency on `Compiler`, which is a bit of a shame.

The ideal solution is to re-structure it so that simple command line input no longer requires Compiler in most cases. And then only passes the input to Compiler when it actually needs to parse actual ink content, or needs to look up line numbers etc. I haven't looked into this deeply enough to see if there are hidden gotchas though!

Another alternative might be to create a dummy Compiler purely to parse commands when no Compiler is otherwise available. But that might create new problems if the Compiler doesn't know it's a dummy, and tries to look up something it's incapable of. Maybe this is a hack on a hack?

In truth, the reason I left it unimplemented is because the good solutions probably aren't super straightforward. But I'm happy to accept a pull request if you manage it - ink-proof is proving really valuable to the community! Thank you!

**Comment by chromy** [comment]
Awesome thanks! I'm glad it has been useful 😄 I've taken a first stab at the pull request over at: https://github.com/inkle/ink/pull/642
