### ISSUE TITLE
Ink flips parameters in externally bound functions; breaks with three parameters

### ISSUE THREAD

**Issue by crustforever** [inkle/ink#70]
Okay so I've created a barebones project where I am seeing this issue:

https://drive.google.com/open?id=0BxMWw45YG-83d1Z0ejlBc2VGWnM (hosted on my google drive because github wouldn't let me upload it)

The scene is Scenes/Main; the script is Scripts/MainStory; the Ink is Resources/Ink/Ink.  The plugin folder is included along with the unitypackage which was downloaded from here: https://github.com/inkle/ink-unity-integration/releases.

The issue is like the title says.  @joethephish said he had seen it before.  I should also mention I am on Windows and Unity version 5.3.4f1.  Let me know if there is any other relevant info to know about my machine if you cannot reproduce this!

**Comment by joethephish** [comment]
Found the problem with the 3 parameters not working - it was just a badly copy/pasted assert that was checking for 2 arguments. Fixed in development branch: 2253b7cbe54832eecb1e9b152aec82f1562393e9

The reversed arguments really should work (and just double checked/tested myself). I think the fix must've somehow escaped the latest ink-unity-integration release, so should be fixed for next release.

**Comment by crustforever** [comment]
Excellent!  Thanks Joe.
