### ISSUE TITLE
Subtitle chunking with automatic progression in Unity

### ISSUE THREAD

**Issue by DrZooDinghy** [inkle/ink#701]
Let's say two NPC characters are talking for some time and an animation + audio is played. This creates quite a lot of text until the user makes an interaction. This is a problem when you want to use subtitles as the text gets pretty long. For subtitles, it would be better if it displayed only a short chunk of text at once.

Is there a way to break down the longer text into chunks that are then played automatically with its associated audio/animation/subtitle in Unity?

**Comment by joningold** [comment]
(That's definitely possible in Unity, but this probably isn't the right forum for that discussion, since it's really a Unity string handling question. )

From an ink point of view, one solution might be to use Continue rather than ContinueMaximally to get one line of ink at a time; the game can then display each line before getting the next one from the ink. The ink script can then simply use line breaks to pace itself out.
