### ISSUE TITLE
[Question] Where does logic get evaluated when popping the evaluation stack?

### ISSUE THREAD

**Issue by crustforever** [inkle/ink#76]
In Story.ProcessChoice(ChoicePoint), the choice text is popped from the evaluation stack and cast "as" a StringValue.  Then it is set to the choice.text field in Choice before returning.  If that choice text contains logic (e.g. {DoSomething()}), where is that evaluated/handled?

**Comment by crustforever** [comment]
Or does the way Ink compile to JSON separate logic and flow control from choices and prepend them such that any embedded choice logic is evaluated in Story.Step() before any choices are handled?

**Comment by joethephish** [comment]
Yeah, exactly. It's compiled so that it works at quite a low level. If you compile this choice: `* {true or false} [test]` what you get in the JSON/runtime is:

        "ev",
        "str",
        "^test",
        "/str",


The `ev` means "begin evaluating logical stuff, pushing stuff to the evaluation stack rather than the output stream". It then generates the text for the choice. 

Now, the condition of the choice:

        1,
        0,
        "||",
        "/ev",

It pushes `1` for `true`, `0` for `false`, then sees the boolean operator `||`, which pops the two values of the stack, and pushes `1` back on. `/ev` then indicates that evaluation is complete.

By this point the stack will contain `[ "test", 1 ]`.

The next construct is the choice point itself:

        {
          "*": ".^.c",
          "flg": 21
        },

This is a choice *point* rather than a literal choice since it says "now generate a choice, with these flags". The flags value of 21 indicates:

* 1: hasCondition - this indicates that it should **pop a value off the evaluation stack** to determine whether or not to display the choice at all.
* 4: hasChoiceOnlyContent - according to square bracket notation, part between the `[` square brackets `]` in the choice. So, it **pops this string off the evaluation stack** too.
* 16: Once only (the default, rather than using sticky choices)

Slightly involved answer, but hopefully answers your question :-)

**Comment by crustforever** [comment]
Thanks!  This is invaluable info for diving into the compiled JSON and the source!
