### ISSUE TITLE
[Question] access data without jumping

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#77]
I would like to know how many remaining options a section of story has, without having to jump to it. More generally, i would like to read information about the state of a story section, without jumping to/running it.

My question is...

In general, is data about story sections accessible independent of the user's current story location? Is the topology of the tree known after the story json has been deserialized? Or is it discovered as the player progresses through it?

Use case: We have several knots which we choose to represent in-game as physical objects. Interactions on that object are handled using the choices for that knot. We would like to be able to hide objects, who's interaction options have been exhausted. 

Here's a concrete example to illustrate the point. Imagine a telephone. When clicked it presents two options

Dial 911
Call Mom

Selecting either displays some bit of narrative text informing the player of the result, then the option is removed. When all options have been exhausted, the telephone will be hidden. 

Currently, the only way (that I know of) to do this is to jump to that knot to read the choiceCount. This has the unintended side effect of executing any functions at that knot.

What I would like to do is query the knot for the number of remaining choices, without having to jump there to do so. 

I fully realize my example is outside the intended scope of the Ink engine. I have no expectation that it be adjusted to make this easier. If, however, this is a simple matter of easing access restrictions to class properties, then I would like to request this. 

Thanks again. We're really enjoying Ink and greatly appreciate the hard work that has gone into designing and maintaining it.

-Jonathan

**Comment by joethephish** [comment]
Hey - interesting use case, but I'm afraid that's not possible :-(

Effectively the JSON is like the equivalent of compiled byte-code. While some aspects of the shape of the original ink file are maintained (like the nesting of stitches-within-knots-within-story), the step-by-step JSON content is in a new format that's not easy to query in the way you're suggesting.

Sorry about that!

**Comment by joethephish** [comment]
Oh, but one thing that we're playing with on a project that we're working on is building extra metadata during the compilation process. If you look at `ChoiceListPlugin.cs` in the ink source, it plucks information out of the ink's parsed tree, and then writes it out separately.

Right now it's pretty hacky. It's project-specific and built directly into the ink codebase, but ideally there would be some kind of plugin architecture to create a separation and allow people to write their own plugins without having to hack the compiler itself!

My guess though is it's still not quite right for your use case, because it's still hard to tell what the number of *remaining* choices would be at any particular point. Part of the reason that's difficult at runtime is that choices can be really dynamic, both in terms of their content, and how many are actually generated, based on specific conditions.

**Comment by joningold** [comment]
Oh, but! On the roadmap is a feature for "peeking ahead" in the story -
essentially, jumping to / running an ink section, getting the output, and
then rolling back the story to before that option was chosen. (We used this
extensively on 80 Days to get the text formatting right.)

Once that's in it'll probably serve your purpose?

jon
