### ISSUE TITLE
Clarify documentation on knot nesting

### ISSUE THREAD

**Issue by wilg** [inkle/ink#803]
I'm confused by the documentation on this. It doesn't really specify how nesting works in knots, just that you can have two *or more* `=` to begin a knot. It appears that the general idea is you can have only two levels of nesting. `=== KNOT` and `= sub_knot`. But maybe it doesn't work exactly that way.

It seems like it would be useful to have arbitrarily deep nesting, but the syntax doesn't seem to support it. If it were like markdown, you could have more equals signs mean deeper nesting (similar to gathers).

```md
# Heading level 1
## Heading level 2	
### Heading level 3	
#### Heading level 4	
##### Heading level 5	
###### Heading level 6	
```

But maybe this is supported in some other way? It would be very useful, since knots allow you to have "local" variable names that are dot-prefixed outside the knot etc. I'm trying to come up with a pattern for organizing my dialogue trees, and it's a bit tricky without knowing what's supported here.

I'd like to do something like:

```ink

= Mission_1 =

// ...

== Convo_joe ==

Joe: Hello, I'm joe!

-> questions

=== questions ===

- How are you
  Joe: Good
- Where are you
  Joe: Earth
- Bye
  -> free_roam

- -> questions

```

I don't think that's exactly possible. (I've reversed the number of = like markdown to make the example work.)

But maybe there's a better way of handling a sort of Skyrim/Fallout sort of dialogue/free-roam model. I have hooked it all up properly in my game, I'm just looking to understand a nice way to structure this common scenario without being too repetitive.

Clarifying how this works in the docs, how nesting works and how it relates to variable naming, would be really useful!

**Comment by joningold** [comment]
There are only two levels - knot and stitch.

 One could have arbitrary levels but in practice there isn’t much need to;
since you can always just make another knot and so forth.

(And we do support arbitrary levels in weaves where they’re really
powerful; having two levels of arbitrary nesting might be pretty confusing?)

**Comment by wilg** [comment]
I see. I didn't realize they had different names. Do you have a recommendation for a pattern like I mention above? I guess just not trying to nest everything inside the mission/quest? I had thought that would be very useful for not getting global variables/names everywhere.

**Comment by joningold** [comment]
There are only two variable scopes: global, and temporary. Global should be
used for anything you want to come back to. That’s unusual for coding but
in practice it’s helpful for narrative because events not being able to see
what else has happened to the player is kinda weird.

The trick is to just get in and write your content, and build as much
structure as it actually requires, which is often not that much. use
labelled choices and gathers to track what’s happened as much as you can,
and only use variables when you really need to.
