### ISSUE TITLE
Is a label a variable? How could I get their states in C#?

### ISSUE THREAD

**Issue by yhslai** [inkle/ink#829]
Given this sample ink script:

    * (greet) [Greet him]
    'Greetings.'
    * (insult) [Insult him]
    'You're face looks as ugly as last time we met.'

If I'd like to do some conditional text in ink, I could just:

    {insult: he punches your face so hard that now you're as ugly.|he greets you as well.}

My question is how to get if the player chose `greet` or `insult` in C#? I know I could just create a new `VAR` and then get `inkStory.variablesState`, but it would make the ink script so much longer because I need to set the VAR after every choice.

**Comment by joningold** [comment]
it's usually a good idea to keep story logic inside ink, as ink generally considers read counts to be internal to the story and they aren't exposed. But if you really need to track all the choices in the code, the best way might be to use tags? 

`* (greet) [ Greet him] #greet_choice `

&c. 

... since then even if your label names change, the tags will still work -- and there shouldn't be too much redundancy as you don't actually need to label most of your choices at all:

```
* (greet) [Greet him] #greet_choice
'Greetings.'
he greets you as well.

* (insult) [Insult him] #insult_choice
'You're face looks as ugly as last time we met.'
he punches your face so hard that now you're as ugly.

```
