### ISSUE TITLE
Voice Over

### ISSUE THREAD

**Issue by tamas-rabel** [inkle/ink#83]
Hi,

We are working on a small adventure game and decided to take ink(le) as our solution for dialogs and scripting.
So far unity integration was piece of cake and the system is very easy to use, but we see no easy way to add voice overs.

So far our ideas were:
- **Label every single line**: This would make the script quite unreadable and hand-managing all the unique ids is not an ideal solution.
- **Add some custom markup per line**: Pretty much sam as above.
- **Use story.currentText as a key**: This seemed to be the least painful solution, but we found no way to get a list of all the possible currentTexts in a story. As option b) we can either parse the .ink or the .json file by hand, but then it's almost like re-writing the whole parser.

We are out of ideas at the moment.
Do you have a recommended method for voice overs?

**Comment by joethephish** [comment]
I'm afraid this isn't something that we've got round to solving for ourselves yet, sorry!

Internally, the ink engine has a path to every piece of content in the story, but we don't currently expose this in any way. If we were to do voice over, we might try to take advantage of this and add it to a public facing API, but it'd not something we've needed to look at yet I'm afraid.

I guess I'd probably be tempted by your custom markup idea, but I agree it's not much fun...

(I don't think you can use story.currentText as a key since if you have two pieces of text that are meant to be voiced in different ways, then they need different recordings?)

**Comment by tamas-rabel** [comment]
Thanks for the quick answer!

We were thinking to use <stitch or knot name>.currentText as the full unique id, which would be correct for 99% of the cases. For the remaining 1%, we can still add some custom markup.

Another idea:
Is there anything open-source which does parsing (like inklecate, or the json parser) and would be easy to modify to just spew out all the possible paths/texts?

**Comment by joethephish** [comment]
There's nothing yet that would quite fit what you need I'm afraid. If you look in the ink source code, there's a very rudimentary "plugin system", which is just a way to add a class to the compiler and build it straight in, so that you can access the parsed tree before it fully compiles it. Search for "ChoiceListPlugin" to see what I mean.

It may still be complicated though - the system is designed so that you can have complex branching within an individual sentence. So, for example:

    Today is {~Monday|Tuesday|Wednesday|Thursday|Friday}. I had {~cereal|sausages and bacon|toast} for breakfast. 

In that example, every sub-string will be exported as an individual text object. There's no point at which that's viewed as a single sentence or as a set of permutations until it actually gets printed out from the engine...

**Comment by crustforever** [comment]
Just a thought:

Could you auto-generate a second version of the JSON -- adding to the text some externally defined function that when executed with a default argument tells the game the VO is missing -- and compare it to the previously generated one, replacing the deltas each time Ink compiles?

Then by hand you replace the argument to that function with the file path to the VO, and that's the JSON you use at runtime.

**Comment by micabytes** [comment]
You may want to take a look at [jInk](https://github.com/micabytes/jink), since it's a different implementation (but also not fully featured yet). Not sure it is actually any better for your purposes, but it does actually implicitly label every line of content ( i use it for saving story state).

**Comment by tamas-rabel** [comment]
I was thinking about something like the label auto-generation, but it doesn't solve the problem of pre-evaluating all the scripting/sequencing. Also, there's no way accessing labels (or even knot-names) from the runtime. Another option would be to auto-generate a function call to the game code (like playAudio(<unique_id>)). Still haven't ruled this option out completely.

After playing around with Inklecate, that's where we are at the moment:

Just with a few lines added to Inklecate source we managed to dump all the texts from a story.
After a bit more fiddling I managed to add a quick evaluation for first-level sequences (including the glue used interally to put the whole line together).
Our modified Inklecate now generates two files:
- The JSON file just as before
- A list of possible currentTexts (given we don't go crazy with glueing and scripting) plus their respective knot/stitch names. The combination of the two will be the unique id.

That's good enough for us at the moment. We can live with not using too complicated stuff, or if we do, we can still add some custom markup just there.

Thanks for all your help, please let me know if you find a better solution or have any other ideas!

**Comment by micabytes** [comment]
Knot.Stitch.# (ignoring empty lines) is also how I generate content IDs in jInk, so I would expect that will work very well for you for most cases.

**Comment by wilg** [comment]
@tamas-rabel Is that modified Inklecate available anywhere? I have much the same problem.

**Comment by tamas-rabel** [comment]
@wilg Not yet, but I can try uploading it somewhere. Will let you know!
