### ISSUE TITLE
VisitCountAtPathString only returns -1

### ISSUE THREAD

**Issue by nullObjectPtr** [inkle/ink#92]
Using a bare-bones ink story like such...
```
== TestKnot ==
this is a test
+ Next -> TestKnot2

== TestKnot2 ==
this is the end
-> END
```

I'm finding that VisitCountAtPathString is consistently -1.

```
story = new Story(text);

int count = story.state.VisitCountAtPathString("TestKnot");
// count is -1

story.ChoosePathString("TestKnot");
int count2 = story.state.VisitCountAtPathString("TestKnot");
// count2 is -1

story.Continue();
int count3 = story.state.VisitCountAtPathString("TestKnot");
// count3 is -1
```

After a story is loaded, and without calling continue, or ChoosePathString my expectation is that
-1 is returned for knots which are not present in the story
0 is returned for knots which are present.

Having stepped through the source code, i notice that in the story state constructor, visit counts are not initialized to 0 for existing knots and stitches.

In my debugging session, the function IncrementVisitCountForContainer is not called after the call to ChoosePathString, or the subsequent call to Continue.

**Comment by joethephish** [comment]
Thanks for the report! It looks you may have found the solution to #85 here. (I just haven't had a chance to take a look/verify myself yet, but it does sound like a missing `IncrementVisitCountForContainer` after `Choose...` is the culprit.)

**Comment by joethephish** [comment]
I just pushed a fix for this in the development branch - see 83c72446dbe53c38821b746d345a0121a31617f9.

It also now returns 0 as the default rather than -1. As far as that method is concerned there's no difference between the path not existing and never having been visited - it would be more complicated (and unnecessary) to initialise all the ones that exist.

Fix will come in a release version soon!
