### ISSUE TITLE
Changing images by referencing ink variables/text

### ISSUE THREAD

**Issue by researchmode** [inkle/ink#93]
Hi, inkle! Firstly, huge thanks for the ink engine - I used it to make a small Adventure Jam game and engine/framework (based on Aaron Broder's blot, but with a few added features including images, sounds and scene changes) : http://gamejolt.com/games/lucerne/150140

However, I've been trying to get Unity to react to ink variables and text, with no success - for example, to change images and sounds/music at specific points in the story. It's probably due to my inexperience with Unity and programming in general, but I've tried various methods to get a sprite renderer to change images by checking the state of the ink story, to no avail. The methods I've tried:

1. ...

        if (_inkStory.currentText == "The text I want game to react to") {
            spriteRenderer.sprite = Image2;
        }

2. in Start:

        int imageChange = (int) _inkStory.variablesState["image_change_test"];

    and then in Update:

        if (imageChange == 1) {
            spriteRenderer.sprite = Image2;
        }

3. ...

        _inkStory.ObserveVariable ("imageChange", (string variableName, object newValue) => {
            if (newValue == "1") {
                spriteRenderer.sprite = Image2;
            }
        });

The game runs without errors (although in the latter examples it says that my variable imageChange's value is never used), so I haven't been able to discern anything by debugging. I can get the image to change when testing with a key press, but it refuses to recognise ink variables or text.

While I'm here (sorry!), I also couldn't get saving or loading to work - I used the code from Running Your Ink, but `_inkStory.state.LoadJson(savedJson);` throws up an error : "the name savedJson does not exist in the current context". I'm guessing it's because the save file doesn't exist at the start of the game, but I'm not sure how to rectify this.

Sorry if this all really basic stuff, but I've been banging my head against it on my own for too long. Any help would be massively appreciated. Thanks!

Tom

**Comment by joethephish** [comment]
Okay, it sounds like you might be hitting different issues for each!

1. Perhaps you need to need to do `_inkStory.currentText.Contains("The text")` since probably your version isn't exactly the same - `currentText` probably has a newline on the end for example.

2. If you move the line from Start line into Update too, so that it's checking its value every frame, then it should work, I think. You've got a couple of problems in your example. Firstly it's creating a new local variable in Start and then throwing it away, and secondly it's never changing after that.

3. The problem with this one is that you're comparing with `"1"` rather than just `1` since it should be an int rather than a string.

**Comment by researchmode** [comment]
Thanks so much! I got the first two approaches working, with your changes - wish I'd posted here sooner!

Apologies if this should be a separate issue, but is there anything I should be adding to stop saving/loading from throwing up the above error in Unity? I'm sure it's just a small tweak or a line of code somewhere, but I've no idea what it is.

**Comment by joethephish** [comment]
Ah apologies I missed that other issue. It sounds like (based on your other problems as well) that you don't fully understand the difference between instance and local variables - so you might want to read up a bit about that. Your `savedJson` variable was defined somewhere where you can't get to it, but without seeing all your code I can't help further with that. Either way it's a C# thing rather than an ink thing.

**Comment by researchmode** [comment]
Ah, ok - thanks for all your help!
